"""Pydantic → TypeScript codegen for lingwen-shared contracts.

Usage:
    uv run python tooling/contracts/generate.py

Reads:
    packages/lingwen-shared/src/lingwen_shared/contracts/python/{world,workspace,quality}.py

Writes:
    packages/lingwen-shared/src/lingwen_shared/contracts/ts/{world,workspace,quality}.ts

Uses pydantic v2's model_json_schema() directly + hand-rolled JSON Schema → TS
converter. Do not edit generated TS manually — run this script after any
Pydantic schema change.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
SHARED_SRC = REPO_ROOT / "packages" / "lingwen-shared" / "src" / "lingwen_shared"
PYTHON_DIR = SHARED_SRC / "contracts" / "python"
TS_DIR = SHARED_SRC / "contracts" / "ts"

MODULES = ["world", "workspace", "quality"]


def _emit_json_schema(module_name: str) -> Path:
    """Use Pydantic v2's model_json_schema() to dump all BaseModels in a module.

    Walks all attributes of the imported module, finds Pydantic v2 BaseModel
    subclasses, and emits a JSON Schema with one entry per model in $defs.
    """
    import importlib

    mod = importlib.import_module(f"lingwen_shared.contracts.python.{module_name}")
    schema: dict = {"$defs": {}}
    for name in dir(mod):
        obj = getattr(mod, name)
        if isinstance(obj, type) and hasattr(obj, "model_json_schema"):
            try:
                sub = obj.model_json_schema()
                schema["$defs"][name] = sub
            except Exception:
                continue
    out = Path(f"/tmp/lingwen_shared_{module_name}_schema.json")
    out.write_text(json.dumps(schema, indent=2), encoding="utf-8")
    return out


def _ts_type_for(prop_schema: dict) -> str:
    """Convert a single JSON Schema property to a TS type string."""
    t = prop_schema.get("type")
    if t == "null":
        return "null"
    if t == "string":
        enum = prop_schema.get("enum")
        if enum:
            return " | ".join(f'"{v}"' for v in enum)
        return "string"
    if t == "integer":
        return "number"
    if t == "number":
        return "number"
    if t == "boolean":
        return "boolean"
    if t == "array":
        items = prop_schema.get("items", {})
        return f"{_ts_type_for(items)}[]"
    if t == "object":
        ref = prop_schema.get("$ref")
        if ref and ref.startswith("#/$defs/"):
            return ref.split("/")[-1]
        # Mapping/Record type
        return "Record<string, unknown>"
    if "anyOf" in prop_schema:
        # Handle Optional types represented as anyOf with null
        parts = [_ts_type_for(s) for s in prop_schema["anyOf"]]
        non_null = [p for p in parts if p != "null"]
        if not non_null:
            return "null"
        joined = " | ".join(non_null) if len(non_null) > 1 else non_null[0]
        if len(non_null) < len(parts):
            return f"{joined} | null"
        return joined
    if "$ref" in prop_schema:
        ref = prop_schema["$ref"]
        if ref.startswith("#/$defs/"):
            return ref.split("/")[-1]
    return "unknown"


def _ts_from_json_schema(module_name: str, schema_path: Path) -> str:
    """Convert a Pydantic JSON Schema dump into a TS module string.

    Walks $defs and emits one ``export interface X { ... }`` per Pydantic model.
    Properties with `?` suffix are optional (not in required[]). Nested model
    references are emitted as bare type names.
    """
    schema = json.loads(schema_path.read_text(encoding="utf-8"))
    defs: dict = schema.get("$defs", {})

    lines = [
        "// AUTO-GENERATED by tooling/contracts/generate.py — do not edit.",
        f"// Source: packages/lingwen-shared/src/lingwen_shared/contracts/python/{module_name}.py",
        "",
    ]
    for name, def_schema in defs.items():
        if not isinstance(def_schema, dict) or def_schema.get("type") != "object":
            continue
        lines.append(f"export interface {name} {{")
        props = def_schema.get("properties", {})
        required = set(def_schema.get("required", []))
        for prop_name, prop_schema in props.items():
            opt = "" if prop_name in required else "?"
            ts_type = _ts_type_for(prop_schema)
            lines.append(f"  {prop_name}{opt}: {ts_type};")
        lines.append("}")
        lines.append("")
    return "\n".join(lines)


def generate() -> int:
    for module_name in MODULES:
        py_file = PYTHON_DIR / f"{module_name}.py"
        if not py_file.is_file():
            print(f"SKIP {module_name}: {py_file} not found", file=sys.stderr)
            continue
        schema_path = _emit_json_schema(module_name)
        ts_content = _ts_from_json_schema(module_name, schema_path)
        out = TS_DIR / f"{module_name}.ts"
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(ts_content, encoding="utf-8")
        print(f"WROTE {out.relative_to(REPO_ROOT)} ({len(ts_content)} bytes)")
    return 0


def main() -> int:
    return generate()


if __name__ == "__main__":
    sys.exit(main())
