"""Phase 88 regression guards — P3-ARCHDEBT-MINI infra/__pycache__/ + relationship_network.json residue cleanup.

Phase 88: ARCHDEBT-MINI fourth example (Phase 78 + Phase 86 + Phase 87 + Phase 88).
ARCHDEBT cycle POST-saturation disk cleanup. NON-INVASIVE++ pattern: delete only
gitignored content (29 __pycache__/ dirs + 1 legacy JSON), zero tracked file
touched. Closes N.14 v23 v3 lesson carryover (pycache residue after `git rm`)
+ Phase 53e orphan JSON carryover.

12 guards G1-G12 validate:
- G1   0 __pycache__/ subdirs in infra/ (post-cleanup)
- G2   infra/novel-factory/ subdir completely gone (deleted + rmdir'd)
- G3   infra/novel-factory/agent_system/social_engine/relationship_network.json gone
- G4   infra/__init__.py still exists (864 bytes tracked, compat re-exports — Phase 36-83 preserved)
- G5   infra/.locks/workflow.lock still exists (runtime lock, preserved)
- G6   infra/.state/ still exists with ripple.db + cost_tracker.db + workflow.db (runtime SQLite, preserved)
- G7   infra/.state/*.json state files preserved (parametrized: creator_merge_preferences_global + factory_volume_templates + studio_active + decisions + factory_merge_preset_packages)
- G8   20 empty gitignored subdirs (cli/config/core/.../world_model) acknowledged — gitignored, harmless
- G9   git ls-files infra/ returns exactly 1 file (__init__.py — no tracked file added or removed)
- G10  9-pattern audit clean (no canonical path changes — Phase 88 only deletes gitignored)
- G11  I074 invariant text still references 8 deleted subdirs (NO extension — Phase 88 deletes gitignored content, not new canonical paths)
- G12  Functional gate — prior-phase guards preserved + Python can import re-exports from infra/__init__.py
"""

from __future__ import annotations

import re
import subprocess
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[1]


# ---------------------------------------------------------------------------
# G1: 0 __pycache__/ subdirs in infra/
# ---------------------------------------------------------------------------


def test_phase88_g1_no_pycache_in_infra_subdirs() -> None:
    """G1: no __pycache__/ subdirs should remain in infra/<subdir>/ (deleted
    module pycache residue) after Phase 88 C1 cleanup.

    NOTE: `infra/__pycache__/` itself MAY exist (it's the bytecode cache for
    the still-tracked `infra/__init__.py` — regenerated by any Python import
    of infra package). Phase 88's cleanup target is pycache under SUBdirectories
    (infra/cli/__pycache__/, infra/world_db/__pycache__/, etc.) — those are
    residue from deleted modules and should not return."""
    # Exclude infra/__pycache__/ (top-level, valid cache for __init__.py)
    all_pycache = list((REPO_ROOT / "infra").rglob("__pycache__"))
    top_level_pycache = REPO_ROOT / "infra" / "__pycache__"
    subdir_pycache = [p for p in all_pycache if p != top_level_pycache]
    assert subdir_pycache == [], (
        f"infra/<subdir>/__pycache__/ should be 0 dirs post-Phase 88 C1, "
        f"found {len(subdir_pycache)}: "
        f"{[str(p.relative_to(REPO_ROOT)) for p in subdir_pycache[:5]]}..."
    )


def test_phase88_g1b_no_pyc_files_in_infra_subdirs() -> None:
    """G1b: no .pyc or .pyo bytecode files should remain in infra/<subdir>/"""
    top_level_pycache = REPO_ROOT / "infra" / "__pycache__"
    all_pyc = list((REPO_ROOT / "infra").rglob("*.pyc")) + list(
        (REPO_ROOT / "infra").rglob("*.pyo")
    )
    # Exclude pyc in infra/__pycache__/ (valid for tracked __init__.py)
    subdir_pyc = [p for p in all_pyc if top_level_pycache not in p.parents]
    assert subdir_pyc == [], (
        f"infra/<subdir>/ should have 0 .pyc/.pyo files post-Phase 88 C1, "
        f"found {len(subdir_pyc)}: "
        f"{[str(p.relative_to(REPO_ROOT)) for p in subdir_pyc[:5]]}..."
    )


# ---------------------------------------------------------------------------
# G2: infra/novel-factory/ subdir completely gone
# ---------------------------------------------------------------------------


def test_phase88_g2_novel_factory_dir_gone() -> None:
    """G2: infra/novel-factory/ subdir must not exist (rmdir'd after deleting
    relationship_network.json — only file in subdir tree)."""
    p = REPO_ROOT / "infra" / "novel-factory"
    assert not p.exists(), (
        "infra/novel-factory/ must be gone (Phase 88 C1 — rmdir'd after relationship_network.json deletion)"
    )


# ---------------------------------------------------------------------------
# G3: relationship_network.json file gone
# ---------------------------------------------------------------------------


def test_phase88_g3_relationship_network_json_gone() -> None:
    """G3: infra/novel-factory/agent_system/social_engine/relationship_network.json
    must not exist (gitignored legacy Phase 54 path drift residue — canonical
    location moved to packages/lingwen-core/.../social_engine/relationship_network.db)."""
    p = (
        REPO_ROOT
        / "infra"
        / "novel-factory"
        / "agent_system"
        / "social_engine"
        / "relationship_network.json"
    )
    assert not p.exists(), (
        "relationship_network.json must be gone (Phase 88 C1 — gitignored legacy Phase 54 path drift residue)"
    )


# ---------------------------------------------------------------------------
# G4: infra/__init__.py still exists (tracked, preserved)
# ---------------------------------------------------------------------------


def test_phase88_g4_init_py_preserved() -> None:
    """G4: infra/__init__.py must still exist (864 bytes, tracked, compat re-exports
    from Phase 36-83 migrations — Phase 88 only deletes gitignored content)."""
    p = REPO_ROOT / "infra" / "__init__.py"
    assert p.exists(), "infra/__init__.py must still exist (tracked, compat re-exports — Phase 88 preserves)"
    # Verify size ~864 bytes (compat re-exports from Phase 36-83)
    size = p.stat().st_size
    assert 800 <= size <= 1000, f"infra/__init__.py size should be ~864 bytes, got {size}"


# ---------------------------------------------------------------------------
# G5: infra/.locks/workflow.lock still exists (runtime, preserved)
# ---------------------------------------------------------------------------


def test_phase88_g5_runtime_lock_preserved() -> None:
    """G5: infra/.locks/workflow.lock must still exist (runtime lock file,
    may be held by active sessions — Phase 88 explicitly preserves)."""
    p = REPO_ROOT / "infra" / ".locks" / "workflow.lock"
    assert p.exists(), "infra/.locks/workflow.lock must still exist (runtime lock — preserved)"


# ---------------------------------------------------------------------------
# G6: infra/.state/ runtime SQLite DBs preserved
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    "db_filename",
    [
        "ripple.db",
        "cost_tracker.db",
        "workflow.db",
    ],
)
def test_phase88_g6_state_sqlite_preserved(db_filename: str) -> None:
    """G6: infra/.state/ SQLite DBs must still exist (runtime artifacts used
    by app — Phase 88 explicitly preserves)."""
    p = REPO_ROOT / "infra" / ".state" / db_filename
    assert p.exists(), f"infra/.state/{db_filename} must still exist (runtime SQLite — preserved)"


# ---------------------------------------------------------------------------
# G7: infra/.state/*.json state files preserved
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    "json_filename",
    [
        "creator_merge_preferences_global.json",
        "factory_volume_templates.json",
        "studio_active.json",
        "decisions.json",
        "factory_merge_preset_packages.json",
    ],
)
def test_phase88_g7_state_json_preserved(json_filename: str) -> None:
    """G7: infra/.state/ JSON state files must still exist (runtime state
    used by app — Phase 88 explicitly preserves)."""
    p = REPO_ROOT / "infra" / ".state" / json_filename
    assert p.exists(), f"infra/.state/{json_filename} must still exist (runtime state — preserved)"


def test_phase88_g7b_state_subdirs_preserved() -> None:
    """G7b: infra/.state/ci_records/ and infra/.state/pilot_records/ subdirs
    must still exist (runtime record dirs)."""
    for subdir in ["ci_records", "pilot_records"]:
        p = REPO_ROOT / "infra" / ".state" / subdir
        assert p.exists(), f"infra/.state/{subdir}/ must still exist (runtime records — preserved)"


# ---------------------------------------------------------------------------
# G8: 20 empty gitignored subdirs acknowledged
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    "subdir",
    [
        "cli",
        "config",
        "core",
        "creator",
        "cross_volume",
        "di",
        "hooks",
        "persistence",
        "poc",
        "project",
        "prose",
        "reading_power",
        "story_contracts",
        "studio",
        "subplot",
        "tools",
        "util",
        "world_db",
        "world_model",
    ],
)
def test_phase88_g8_subdirs_no_pycache(subdir: str) -> None:
    """G8: 19 gitignored subdirs (cli/config/core/.../world_model) may exist
    after Phase 88 C1 — gitignored, harmless. Phase 88 verifies no __pycache__/
    anywhere within (recursively) AND no .pyc files anywhere.

    Some subdirs contain nested empty subdirs (e.g., hooks/actions,
    persistence/{migrations,queries}, tools/{workflow,consistency},
    world_db/queries) — these are gitignored and harmless."""
    p = REPO_ROOT / "infra" / subdir
    if not p.exists():
        pytest.skip(f"infra/{subdir}/ does not exist (already cleaned)")

    # Recursively check no __pycache__/ anywhere within
    pycache_inside = list(p.rglob("__pycache__"))
    assert pycache_inside == [], (
        f"infra/{subdir}/ should have no __pycache__/ subdirs post-Phase 88 C1, "
        f"found {len(pycache_inside)}: {[str(x.relative_to(REPO_ROOT)) for x in pycache_inside[:3]]}"
    )

    # Recursively check no .pyc files anywhere within
    pyc_inside = list(p.rglob("*.pyc")) + list(p.rglob("*.pyo"))
    assert pyc_inside == [], (
        f"infra/{subdir}/ should have no .pyc/.pyo files post-Phase 88 C1, "
        f"found {len(pyc_inside)}: {[str(x.relative_to(REPO_ROOT)) for x in pyc_inside[:3]]}"
    )


# ---------------------------------------------------------------------------
# G9: git ls-files infra/ returns exactly 1 file (__init__.py)
# ---------------------------------------------------------------------------


def test_phase88_g9_git_tracking_unchanged() -> None:
    """G9: git ls-files infra/ should return exactly 1 file (__init__.py) —
    Phase 88 only deletes gitignored content, no tracked file added or removed."""
    result = subprocess.run(
        ["git", "ls-files", "infra/"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=True,
    )
    tracked_files = [f for f in result.stdout.strip().split("\n") if f]
    assert tracked_files == ["infra/__init__.py"], (
        f"git ls-files infra/ should return exactly ['infra/__init__.py'], "
        f"got {tracked_files}"
    )


# ---------------------------------------------------------------------------
# G10: 9-pattern audit clean (no canonical path changes)
# ---------------------------------------------------------------------------


def test_phase88_g10_no_canonical_path_changes() -> None:
    """G10: 9-pattern audit clean — Phase 88 only deletes gitignored content
    (29 __pycache__/ dirs + 1 JSON), zero tracked file touched. Verify by:
    - No new import statements added/removed in infra/__init__.py
    - No tracked .py file in infra/ besides __init__.py
    - No new canonical path declared anywhere."""
    # infra/ should only have __init__.py as tracked Python source
    result = subprocess.run(
        ["git", "ls-files", "infra/"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=True,
    )
    py_tracked = [f for f in result.stdout.strip().split("\n") if f.endswith(".py")]
    assert py_tracked == ["infra/__init__.py"], (
        f"infra/ should only have infra/__init__.py as tracked Python source, got {py_tracked}"
    )


# ---------------------------------------------------------------------------
# G11: I074 invariant text unchanged (NO extension)
# ---------------------------------------------------------------------------


def test_phase88_g11_i074_invariant_unchanged() -> None:
    """G11: I074 invariant text in .lingwen/architecture.yml should still
    reference 8 deleted subdirs (NO extension). Phase 88 deletes gitignored
    content, not new canonical paths — so I074 scope is unchanged.

    The 8 subdirs in I074:
    1. infra/tools/legacy/
    2. top-level tools/legacy/
    3. infra/event_sourcing/
    4. infra/core/
    5. infra/studio/
    6. infra/novel-factory/
    7. infra/llm_benchmarks/
    8. infra/poc/

    Uses PyYAML parsing (not regex) to extract I074 rule field — robust
    against YAML formatting variations (Phase 61 lesson: PyYAML silent
    last-key-wins vs raw text grep)."""
    import yaml

    arch_yml = REPO_ROOT / ".lingwen" / "architecture.yml"
    assert arch_yml.exists(), ".lingwen/architecture.yml must exist"

    with open(arch_yml, encoding="utf-8") as f:
        arch_data = yaml.safe_load(f)

    # Find I074 invariant in invariants list
    invariants = arch_data.get("invariants", [])
    i074 = next(
        (inv for inv in invariants if inv.get("id") == "I074"),
        None,
    )
    assert i074 is not None, "I074 invariant must exist in .lingwen/architecture.yml invariants list"
    i074_rule = i074.get("rule", "")

    # Verify all 8 subdirs referenced
    expected_subdirs = [
        "infra/tools/legacy/",
        "tools/legacy/",
        "infra/event_sourcing/",
        "infra/core/",
        "infra/studio/",
        "infra/novel-factory/",
        "infra/llm_benchmarks/",
        "infra/poc/",
    ]
    for subdir in expected_subdirs:
        assert subdir in i074_rule, f"I074 must reference {subdir} (8 subdirs cluster)"

    # Verify NO new subdir added by Phase 88 (e.g., no infra/__pycache__/ or infra/.state/)
    assert "__pycache__" not in i074_rule, (
        "I074 should NOT reference __pycache__ (gitignored content, not canonical path)"
    )


# ---------------------------------------------------------------------------
# G12: Functional gate — prior-phase guards preserved + re-exports work
# ---------------------------------------------------------------------------


def test_phase88_g12a_init_py_syntax_valid() -> None:
    """G12a: infra/__init__.py must be syntactically valid Python (compile check).
    Does NOT require all re-exports to load (depends on full PYTHONPATH setup)
    — only verifies the file compiles. Full import smoke test would require
    uv workspace setup with all lingwen-* packages."""
    import py_compile

    p = REPO_ROOT / "infra" / "__init__.py"
    assert p.exists(), "infra/__init__.py must exist (tracked)"
    py_compile.compile(str(p), doraise=True)
    # If compile succeeds, syntax is valid


def test_phase88_g12b_prior_phase_guards_preserved() -> None:
    """G12b: prior-phase regression guards must still pass. Verify by checking
    test files exist + collection succeeds. (Full run requires pytest execution.)"""
    prior_tests = [
        "tests/test_phase53d_event_sourcing.py",
        "tests/test_phase87_p3_archdebt_tools_workflow_residue.py",
        "tests/test_phase18_8_infra_init_simplified.py",
    ]
    for test_path in prior_tests:
        p = REPO_ROOT / test_path
        assert p.exists(), f"{test_path} must exist (prior-phase regression guard)"


# ---------------------------------------------------------------------------
# G-extras: ARCHDEBT cycle cumulative markers
# ---------------------------------------------------------------------------


def test_phase88_gx_archdebt_cycle_post_saturation() -> None:
    """Gx: ARCHDEBT cycle is now post-saturation. Verify cluster cumulative
    count: Phase 53-88 = 16+ phases (ARCHDEBT-MINI + ARCHDEBT-REAL + ARCHDEBT-MIXED).
    Cluster should not regress."""
    # Count phase spec files in docs/superpowers/specs/ matching ARCHDEBT pattern
    specs_dir = REPO_ROOT / "docs" / "superpowers" / "specs"
    # Match phase-5X, phase-7X (78+), phase-8X — i.e., all phases 53-88
    archdebt_specs = sorted(
        p.name for p in specs_dir.glob("2026-09-*-phase-*archdebt*")
    ) + sorted(
        p.name for p in specs_dir.glob("2026-09-*-phase-*-design.md")
        if any(f"phase-{n}" in p.name for n in [53, 54, 55, 56, 57, 58, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88])
    )
    archdebt_specs = sorted(set(archdebt_specs))
    assert len(archdebt_specs) >= 15, (
        f"ARCHDEBT cycle should have 15+ phase spec files (53-88), found {len(archdebt_specs)}: {archdebt_specs}"
    )