全文大纲_CARE:
- changelog: 测试保存版本
  created_at: '2026-05-20 01:08:43.688914'
  file_hash: 43741b6619d3363b11a2f137bed22d22
  file_path: 提示词模板库/01_大纲生成/全文大纲_CARE.md
  status: active
  template_id: 全文大纲_CARE
  version: v1.0.0
- changelog: 添加新章节结构
  created_at: '2026-05-20 01:09:26.709077'
  file_hash: 43741b6619d3363b11a2f137bed22d22
  file_path: 提示词模板库/01_大纲生成/全文大纲_CARE.md
  status: active
  template_id: 全文大纲_CARE
  version: v1.0.1
