"""lingwen_shared.contracts.ts — auto-generated TypeScript types (do not edit).

Generated by tooling/contracts/generate.py from contracts/python/.
Regenerate after any Pydantic schema change:
    uv run python tooling/contracts/generate.py
"""
