// AUTO-GENERATED by tooling/contracts/generate.py — do not edit.
// Source: packages/lingwen-shared/src/lingwen_shared/contracts/python/creator.py

export interface CreatorOutlineHighlightLine {
  text: string;
  highlighted?: boolean;
}

export interface CreatorVolumeApplyTemplateRequest {
  template_id: string;
  max_chapter?: number | null;
}

export interface CreatorVolumeApplyTemplateResponse {
  template_id: string;
  template_name: string;
  volumes: CreatorVolumePlanEntry[];
}

export interface CreatorVolumeDeleteTemplateResponse {
  id: string;
  deleted: boolean;
}

export interface CreatorVolumeDeviation {
  type: string;
  severity: string;
  chapter: number;
  volume_label?: string | null;
  message: string;
}

export interface CreatorVolumeFactoryDeleteResponse {
  id: string;
  deleted: boolean;
}

export interface CreatorVolumeFactoryPublishRequest {
  template_id: string;
}

export interface CreatorVolumeFactoryPublishResponse {
  id: string;
  name: string;
  description: string;
}

export interface CreatorVolumeFactoryPullRequest {
  template_ids: string[];
}

export interface CreatorVolumeFactoryPullResponse {
  imported: number;
  total: number;
  template_ids: string[];
}

export interface CreatorVolumeMergeRequest {
  volumes: CreatorVolumePlanEntry[];
  start_index: number;
  end_index: number;
  label?: string | null;
  core_conflict?: string | null;
}

export interface CreatorVolumeMergeResponse {
  volumes: CreatorVolumePlanEntry[];
  merged_label: string;
  merged_range: string;
}

export interface CreatorVolumePlanDiffChange {
  type: string;
  label: string;
  message: string;
  details?: string[];
}

export interface CreatorVolumePlanDiffResponse {
  has_changes: boolean;
  changes: CreatorVolumePlanDiffChange[];
  global_outline_excerpt?: string;
  global_outline_path?: string;
  highlight_volume_labels?: string[];
  global_outline_lines?: CreatorOutlineHighlightLine[];
}

export interface CreatorVolumePlanEntry {
  label: string;
  start_chapter: number;
  end_chapter: number;
  core_conflict?: string;
  locked?: boolean;
  locked_at?: string | null;
}

export interface CreatorVolumePlanResponse {
  slug: string;
  global_outline_path: string;
  state_path: string;
  revision: string;
  volumes: CreatorVolumePlanEntry[];
  locked_volume_count: number;
  deviations: CreatorVolumeDeviation[];
  deviation_count: number;
  alert_count: number;
}

export interface CreatorVolumePlanSaveRequest {
  volumes: CreatorVolumePlanEntry[];
  expected_revision?: string | null;
}

export interface CreatorVolumeRenameTemplateRequest {
  name: string;
  description?: string | null;
  version_label?: string | null;
}

export interface CreatorVolumeRenameTemplateResponse {
  id: string;
  name: string;
  description: string;
  version_label?: string | null;
}

export interface CreatorVolumeSaveTemplateRequest {
  name: string;
  volumes: CreatorVolumePlanEntry[];
  max_chapter?: number | null;
  description?: string | null;
  version_label?: string | null;
}

export interface CreatorVolumeSaveTemplateResponse {
  id: string;
  name: string;
  description: string;
}

export interface CreatorVolumeSplitRequest {
  volumes: CreatorVolumePlanEntry[];
  volume_index: number;
  split_at_chapter: number;
  first_label?: string | null;
  second_label?: string | null;
}

export interface CreatorVolumeSplitResponse {
  volumes: CreatorVolumePlanEntry[];
  first_label: string;
  second_label: string;
  first_range: string;
  second_range: string;
}

export interface CreatorVolumeSummaryGenerateRequest {
  start_chapter: number;
  end_chapter: number;
}

export interface CreatorVolumeSummaryGenerateResponse {
  path: string;
  written?: boolean;
}

export interface CreatorVolumeTemplateApproval {
  id: string;
  template_id: string;
  scope?: string;
  status?: string;
  version_label?: string | null;
  previous_label?: string | null;
  submitted_at?: string | null;
  resolved_at?: string | null;
  reject_reason?: string;
  submit_note?: string;
  resolve_note?: string;
  current_assignee?: string;
  current_assignees?: string[];
  or_signing?: boolean;
  has_volumes_snapshot?: boolean;
  chain_step?: number;
  chain_total?: number;
  chain_progress?: string;
  chain_log?: Record<string, unknown>[];
  hours_pending?: number | null;
}

export interface CreatorVolumeTemplateApprovalAuditExportResponse {
  schema_version?: string;
  count: number;
  approvals: CreatorVolumeTemplateApproval[];
}

export interface CreatorVolumeTemplateApprovalBatchRequest {
  approval_ids: string[];
  assignee?: string;
  resolve_note?: string;
  reason?: string;
  force?: boolean;
}

export interface CreatorVolumeTemplateApprovalBatchResponse {
  approved?: number;
  rejected?: number;
  total: number;
  results?: CreatorVolumeTemplateApprovalBatchResult[];
}

export interface CreatorVolumeTemplateApprovalBatchResult {
  id: string;
  ok: boolean;
  status?: string | null;
  chain_advanced?: boolean | null;
  error?: string | null;
}

export interface CreatorVolumeTemplateApprovalChainConfig {
  required_steps?: number;
  step_assignees?: string[];
  step_assignee_groups?: string[][] | null;
}

export interface CreatorVolumeTemplateApprovalDriftResponse {
  approval_id: string;
  template_id: string;
  drifted: boolean;
  diff_summary?: Record<string, unknown>;
  force?: boolean;
}

export interface CreatorVolumeTemplateApprovalHistoryResponse {
  approvals: CreatorVolumeTemplateApproval[];
}

export interface CreatorVolumeTemplateApprovalListResponse {
  approvals: CreatorVolumeTemplateApproval[];
}

export interface CreatorVolumeTemplateApprovalOverdueResponse {
  overdue_count: number;
  approvals?: CreatorVolumeTemplateApproval[];
}

export interface CreatorVolumeTemplateApprovalRejectRequest {
  reason?: string;
  resolve_note?: string;
}

export interface CreatorVolumeTemplateApprovalResolveRequest {
  assignee?: string;
  resolve_note?: string;
  force?: boolean;
}

export interface CreatorVolumeTemplateApprovalSlaConfig {
  timeout_hours?: number;
  email_on_submit?: boolean;
  email_on_reject?: boolean;
  email_on_overdue?: boolean;
}

export interface CreatorVolumeTemplateApprovalSnapshotDiffResponse {
  approval_id: string;
  template_id: string;
  has_volumes_snapshot?: boolean;
  diff_summary?: Record<string, unknown>;
  visual_diff?: Record<string, unknown>;
}

export interface CreatorVolumeTemplateApprovalSubmitRequest {
  version_label?: string | null;
  submit_note?: string;
}

export interface CreatorVolumeTemplateApprovalTransferRequest {
  to_assignee: string;
  note?: string;
}

export interface CreatorVolumeTemplateChangelogDiffSummary {
  changed?: boolean;
  lines_added?: number;
  lines_removed?: number;
  snippet?: string[];
}

export interface CreatorVolumeTemplateChangelogEntry {
  version_label?: string | null;
  previous_label?: string | null;
  changed_at?: string | null;
  diff_summary?: CreatorVolumeTemplateChangelogDiffSummary | null;
  visual_diff?: CreatorVolumeTemplateChangelogVisualDiff | null;
  can_rollback?: boolean;
}

export interface CreatorVolumeTemplateChangelogResponse {
  template_id: string;
  entries: CreatorVolumeTemplateChangelogEntry[];
}

export interface CreatorVolumeTemplateChangelogVisualDiff {
  before?: string;
  after?: string;
  lines?: CreatorVolumeTemplateChangelogVisualLine[];
}

export interface CreatorVolumeTemplateChangelogVisualLine {
  type: string;
  text: string;
}

export interface CreatorVolumeTemplateExportResponse {
  schema_version: string;
  templates: Record<string, unknown>[];
  count: number;
}

export interface CreatorVolumeTemplateImportRequest {
  templates: Record<string, unknown>[];
  replace?: boolean;
}

export interface CreatorVolumeTemplateImportResponse {
  imported: number;
  total: number;
  replaced: boolean;
}

export interface CreatorVolumeTemplateInfo {
  id: string;
  name: string;
  description: string;
  builtin?: boolean;
  scope?: string;
  version_label?: string | null;
  version_semver_valid?: boolean;
  version_changelog?: Record<string, unknown>[];
}

export interface CreatorVolumeTemplateListResponse {
  templates: CreatorVolumeTemplateInfo[];
}

export interface CreatorVolumeTemplateRollbackRequest {
  version_label?: string | null;
  changelog_index?: number | null;
}

export interface CreatorVolumeTemplateRollbackResponse {
  id: string;
  version_label?: string | null;
  rolled_back_to?: string | null;
}

export interface CreatorVolumeTemplateSyncRequest {
  source_slugs: string[];
}

export interface CreatorVolumeTemplateSyncResponse {
  imported: number;
  total: number;
  sources: string[];
}

export interface CreatorVolumeTemplateSyncSource {
  slug: string;
  name: string;
  template_count: number;
}

export interface CreatorVolumeTemplateSyncSourcesResponse {
  sources: CreatorVolumeTemplateSyncSource[];
}

export interface CreatorVolumeTemplateVersionRequest {
  version_label?: string | null;
}

export interface CreatorVolumeTemplateVersionResponse {
  id: string;
  version_label?: string | null;
}
