// AUTO-GENERATED by tooling/contracts/generate.py — do not edit.
// Source: packages/lingwen-shared/src/lingwen_shared/contracts/python/creator.py

export interface CreatorAgentPlanRequest {
  action_label: string;
  base_text?: string | null;
  lens?: string | null;
  provider_mode?: string | null;
}

export interface CreatorAgentPlanResponse {
  results?: Record<string, unknown>[];
  annotations?: Record<string, unknown>[];
  advice?: string | null;
}

export interface CreatorBatchHistoryExportResponse {
  schema_version?: string;
  count?: number;
  jobs?: Record<string, unknown>[];
}

export interface CreatorBatchHistoryResponse {
  jobs?: Record<string, unknown>[];
}

export interface CreatorBodySaveRequest {
  chapter_id: number;
  body: string;
  revision?: string | null;
  metadata?: Record<string, unknown> | null;
}

export interface CreatorChapterPreview {
  chapter_id: number;
  project_slug: string;
  outline: string;
  body: string;
  last_modified?: string | null;
}

export interface CreatorDashboardChapterPreview {
  chapter_id: number;
  project_slug: string;
  outline?: string;
  body?: string;
}

export interface CreatorDashboardOverview {
  project_slug: string;
  overview?: Record<string, unknown>;
}

export interface CreatorDiffCollabNotesRequest {
  notes?: Record<string, unknown>;
}

export interface CreatorDiffCollabNotesResponse {
  notes?: Record<string, unknown>;
  count?: number;
}

export interface CreatorDocxExportRequest {
  mode?: string;
  start_chapter?: number | null;
  end_chapter?: number | null;
  title?: string | null;
  author?: string | null;
  description?: string | null;
  submission_sample_count?: number | null;
}

export interface CreatorEpubExportRequest {
  mode?: string;
  start_chapter?: number | null;
  end_chapter?: number | null;
  title?: string | null;
  author?: string | null;
  description?: string | null;
  submission_sample_count?: number | null;
}

export interface CreatorFactoryMergePresetOperationResponse {
  imported: number;
  skipped?: number;
  total: number;
  package_ids?: string[];
  skipped_package_ids?: string[];
}

export interface CreatorLogicCheckResponse {
  violations?: Record<string, unknown>[];
  summary?: string | null;
}

export interface CreatorMemoryAnnotationRequest {
  note?: string | null;
  pinned?: boolean | null;
}

export interface CreatorMemoryAnnotationResponse {
  asset_id: string;
  note?: string | null;
  pinned?: boolean;
  updated_at?: string | null;
}

export interface CreatorMemoryAssetItem {
  id: string;
  kind: string;
  name: string;
  excerpt: string;
  chapters?: number[];
  editable?: boolean;
  placeholder?: boolean;
  source?: string;
  note?: string | null;
  pinned?: boolean;
}

export interface CreatorMemoryAssetsResponse {
  slug: string;
  memory_available: boolean;
  memory_rag_enabled: boolean;
  items?: CreatorMemoryAssetItem[];
}

export interface CreatorMemoryQueryRequest {
  query: string;
  scope?: string;
  top_k?: number | null;
}

export interface CreatorMemoryQueryResponse {
  query: string;
  memory_available: boolean;
  used_fallback: boolean;
  results?: CreatorMemoryQueryResult[];
}

export interface CreatorMemoryQueryResult {
  id: string;
  snippet: string;
  score?: number;
  chapter?: number | null;
  kind?: string;
  source?: string;
  citation?: string | null;
  asset_name?: string | null;
  matched_terms?: string[];
}

export interface CreatorMergePreferencesExportResponse {
  schema_version: string;
  project: Record<string, unknown>;
  global?: Record<string, unknown>;
}

export interface CreatorMergePreferencesImportRequest {
  schema_version?: string | null;
  project?: Record<string, unknown> | null;
  global?: Record<string, unknown> | null;
  scope?: string;
}

export interface CreatorMergePreferencesResponse {
  pillars_merge_source: string;
  global_outline_merge_source: string;
  merge_snapshot_id?: string | null;
  pillars_merge_snapshot_id?: string | null;
  global_outline_merge_snapshot_id?: string | null;
  uses_global_default?: boolean;
}

export interface CreatorMergePresetChangelogEntry {
  changed_at?: string | null;
  action?: string;
  changed_fields?: string[];
  snapshot?: Record<string, unknown>;
}

export interface CreatorMergePresetChangelogResponse {
  package_id: string;
  entry_count: number;
  entries?: CreatorMergePresetChangelogEntry[];
}

export interface CreatorMergePresetConflict {
  type: string;
  package_id: string;
  dependency_id?: string | null;
  path?: string[];
  message?: string;
}

export interface CreatorMergePresetConflictFix {
  id: string;
  conflict_type: string;
  package_id: string;
  action: string;
  dependency_id?: string | null;
  version_label?: string | null;
  label?: string;
  applicable?: boolean;
}

export interface CreatorMergePresetConflictsResponse {
  conflict_count: number;
  conflicts?: CreatorMergePresetConflict[];
}

export interface CreatorMergePresetGraphEdge {
  from_pkg: string;
  to: string;
  relation?: string;
}

export interface CreatorMergePresetGraphNode {
  id: string;
  name: string;
  scope: string;
  version_label?: string | null;
}

export interface CreatorMergePresetGraphResponse {
  node_count: number;
  edge_count: number;
  nodes?: CreatorMergePresetGraphNode[];
  edges?: CreatorMergePresetGraphEdge[];
}

export interface CreatorMergePresetImportPreviewResponse {
  added?: string[];
  updated?: Record<string, unknown>[];
  removed?: string[];
  unchanged_count?: number;
  replace?: boolean;
}

export interface CreatorMergePresetPackageDetail {
  id: string;
  name: string;
  description?: string;
  builtin?: boolean;
  scope?: string;
  version_label?: string | null;
  version_semver_valid?: boolean;
  depends_on?: string[];
  pillars_merge_source: string;
  global_outline_merge_source: string;
}

export interface CreatorMergePresetPackageSummary {
  id: string;
  name: string;
  description?: string;
  builtin?: boolean;
  scope?: string;
  version_label?: string | null;
  version_semver_valid?: boolean;
  depends_on?: string[];
  pillars_merge_source: string;
  global_outline_merge_source: string;
}

export interface CreatorMergePresetPublishRequest {
  package_id: string;
}

export interface CreatorMergePresetToposortResponse {
  order?: string[];
  cyclic?: boolean;
  package_count?: number;
  nodes?: Record<string, unknown>[];
  edges?: Record<string, unknown>[];
  edge_count?: number;
}

export interface CreatorModelsResponse {
  providers?: Record<string, unknown>[];
}

export interface CreatorOnboardingDigestDeadLetterReplayRequest {
  index?: number;
}

export interface CreatorOnboardingDigestDeadLetterReplayResponse {
  replayed: boolean;
  index: number;
  channel?: string | null;
  retry_queue_size?: number;
  dead_letter_count?: number;
}

export interface CreatorOnboardingDigestDeadLetterResponse {
  item_count: number;
  items?: CreatorOnboardingDigestRetryItem[];
}

export interface CreatorOnboardingDigestDispatchResponse {
  sent?: boolean;
  skipped?: boolean;
  reason?: string | null;
  last_sent_at?: string | null;
}

export interface CreatorOnboardingDigestDispatchStats {
  sent_total?: number;
  failed_total?: number;
  last_sent_at?: string | null;
  last_failure_at?: string | null;
}

export interface CreatorOnboardingDigestRetryItem {
  channel: string;
  error?: string;
  queued_at?: string | null;
  attempts?: number;
  next_retry_at?: string | null;
}

export interface CreatorOnboardingDigestRetryProcessResponse {
  retried: number;
  remaining: number;
  dead_letter_count?: number;
}

export interface CreatorOnboardingDigestRetryQueueResponse {
  item_count: number;
  items?: CreatorOnboardingDigestRetryItem[];
}

export interface CreatorOnboardingDigestScheduleConfig {
  enabled?: boolean;
  interval_hours?: number;
  last_sent_at?: string | null;
  channels?: string[];
  handle_channels?: Record<string, unknown>;
  quiet_hours_start?: number | null;
  quiet_hours_end?: number | null;
  handle_quiet_hours?: Record<string, unknown>;
  channel_retry_config?: Record<string, unknown>;
}

export interface CreatorOnboardingDigestScheduleSaveRequest {
  enabled?: boolean;
  interval_hours?: number;
  channels?: string[];
  handle_channels?: Record<string, unknown>;
  quiet_hours_start?: number | null;
  quiet_hours_end?: number | null;
  handle_quiet_hours?: Record<string, unknown>;
  channel_retry_config?: Record<string, unknown>;
}

export interface CreatorOnboardingEmailConfig {
  enabled?: boolean;
  to_addresses?: string[];
  mention_handles?: string[];
  smtp_host?: string;
  smtp_port?: number;
  smtp_user?: string;
  smtp_use_tls?: boolean;
  from_address?: string;
}

export interface CreatorOnboardingEmailSaveRequest {
  enabled?: boolean;
  to_addresses?: string[];
  mention_handles?: string[];
  smtp_host?: string;
  smtp_port?: number;
  smtp_user?: string;
  smtp_password?: string | null;
  smtp_use_tls?: boolean;
  from_address?: string;
}

export interface CreatorOnboardingNotesRequest {
  step_notes: Record<string, unknown>;
}

export interface CreatorOnboardingNotification {
  id: string;
  step_id: string;
  handle: string;
  note_excerpt: string;
  created_at?: string | null;
  read?: boolean;
}

export interface CreatorOnboardingNotificationDigestGroup {
  handle: string;
  count: number;
  steps?: CreatorOnboardingNotificationDigestStep[];
  latest_at?: string | null;
  excerpts?: string[];
}

export interface CreatorOnboardingNotificationDigestResponse {
  unread: number;
  group_count: number;
  groups?: CreatorOnboardingNotificationDigestGroup[];
}

export interface CreatorOnboardingNotificationDigestStep {
  step_id: string;
  count: number;
}

export interface CreatorOnboardingNotificationsAckRequest {
  notification_ids?: string[];
  all_notifications?: boolean;
  handle?: string | null;
}

export interface CreatorOnboardingNotificationsAckResponse {
  acked: number;
  unread: number;
}

export interface CreatorOnboardingNotificationsResponse {
  notifications: CreatorOnboardingNotification[];
  unread: number;
  handles?: string[];
}

export interface CreatorOnboardingProgressRequest {
  completed_step_ids?: string[];
  step_notes?: Record<string, unknown> | null;
}

export interface CreatorOnboardingProgressResponse {
  completed_step_ids: string[];
  auto_completed_step_ids?: string[];
  step_notes?: Record<string, unknown>;
  step_mentions?: Record<string, unknown>;
  progress_pct: number;
}

export interface CreatorOnboardingResponse {
  slug: string;
  creation_mode: string;
  mode_label: string;
  max_chapter: number;
  steps: CreatorOnboardingStep[];
  checklist_doc: string;
  smoke_command: string;
  onboarding_doc: string;
  completed_step_ids?: string[];
  auto_completed_step_ids?: string[];
  step_notes?: Record<string, unknown>;
  step_mentions?: Record<string, unknown>;
  unread_mention_count?: number;
  progress_pct?: number;
  wizard_panel_dismissed?: boolean;
  wizard_panel_collapsed?: boolean;
}

export interface CreatorOnboardingStep {
  id: string;
  title: string;
  detail: string;
  note?: string;
  mentions?: string[];
}

export interface CreatorOnboardingWebhookConfig {
  enabled?: boolean;
  url?: string;
  mention_handles?: string[];
  signing_secret?: string;
}

export interface CreatorOnboardingWebhookDispatchResponse {
  dispatched?: number;
  skipped?: boolean;
  status?: number | null;
  error?: string | null;
}

export interface CreatorOnboardingWebhookSaveRequest {
  enabled?: boolean;
  url?: string;
  mention_handles?: string[];
  signing_secret?: string | null;
}

export interface CreatorOutlineHighlightLine {
  text: string;
  highlighted?: boolean;
}

export interface CreatorOutlineSaveRequest {
  chapter_id: number;
  outline: string;
  revision?: string | null;
}

export interface CreatorOverviewResponse {
  project_slug: string;
  overview?: Record<string, unknown>;
  last_updated?: string | null;
}

export interface CreatorPreferencesResponse {
  creation_mode: "companion" | "advance" | "studio";
  quality_profile: string;
  fail_severity?: string | null;
  run_prose_calibration?: boolean;
  run_llm_judge?: boolean;
  run_golden_set?: boolean;
  notify_per_chapter?: boolean;
  advance_volume_summary?: boolean;
}

export interface CreatorPreferencesSaveRequest {
  creation_mode?: "companion" | "advance" | "studio" | null;
  quality_profile?: string | null;
  fail_severity?: string | null;
  run_prose_calibration?: boolean | null;
  run_llm_judge?: boolean | null;
  run_golden_set?: boolean | null;
  notify_per_chapter?: boolean | null;
  advance_volume_summary?: boolean | null;
}

export interface CreatorPublishEntry {
  id: string;
  platform: string;
  include_outline: boolean;
  intro?: string;
  mode: string;
  status: string;
  message: string;
  created_at: string;
  adapter_id?: string | null;
  connection?: string | null;
  external_url?: string | null;
  package_hint?: string | null;
}

export interface CreatorPublishHistoryResponse {
  slug: string;
  entries?: CreatorPublishEntry[];
}

export interface CreatorPublishPlatform {
  id: string;
  label: string;
  connection: string;
  capabilities: CreatorPublishPlatformCapabilities;
}

export interface CreatorPublishPlatformCapabilities {
  supports_submission_pack?: boolean;
  supports_full_book?: boolean;
  oauth_required?: boolean;
  max_intro_chars?: number;
}

export interface CreatorPublishPlatformsResponse {
  slug: string;
  platforms?: CreatorPublishPlatform[];
}

export interface CreatorPublishRequest {
  platform: string;
  include_outline?: boolean;
  intro?: string;
  mode?: string;
}

export interface CreatorSettingsDiffPart {
  changed: boolean;
  lines_added: number;
  lines_removed: number;
  snippet?: string[];
}

export interface CreatorSettingsDocsDiffResponse {
  has_changes: boolean;
  pillars: CreatorSettingsDiffPart;
  global_outline: CreatorSettingsDiffPart;
}

export interface CreatorSettingsDocsResponse {
  slug: string;
  pillars_path: string;
  global_outline_path: string;
  pillars_text: string;
  global_outline_text: string;
  pillars_revision: string;
  global_outline_revision: string;
}

export interface CreatorSettingsDocsSaveRequest {
  pillars_text?: string | null;
  global_outline_text?: string | null;
  expected_pillars_revision?: string | null;
  expected_global_outline_revision?: string | null;
  pillars_merge_source?: string | null;
  global_outline_merge_source?: string | null;
  merge_snapshot_id?: string | null;
  pillars_merge_snapshot_id?: string | null;
  global_outline_merge_snapshot_id?: string | null;
}

export interface CreatorSettingsHistoryResponse {
  slug: string;
  snapshots?: CreatorSettingsHistorySnapshot[];
  count: number;
}

export interface CreatorSettingsHistoryRestoreRequest {
  snapshot_id: string;
}

export interface CreatorSettingsHistorySnapshot {
  id: string;
  saved_at?: string | null;
  label: string;
  pillars_excerpt: string;
  global_outline_excerpt: string;
  pillars_lines: number;
  global_outline_lines: number;
}

export interface CreatorSettingsMergeFieldPreview {
  source: string;
  vs_disk: CreatorSettingsDiffPart;
  vs_editor: CreatorSettingsDiffPart;
}

export interface CreatorSettingsMergeStrategyResponse {
  pillars: CreatorSettingsMergeFieldPreview;
  global_outline: CreatorSettingsMergeFieldPreview;
}

export interface CreatorSettingsThreeWayDiffResponse {
  has_changes: boolean;
  pillars: CreatorSettingsDiffPart;
  global_outline: CreatorSettingsDiffPart;
  has_history?: boolean;
  history_snapshot_id?: string | null;
  disk_vs_history?: CreatorSettingsThreeWayPair | null;
  editor_vs_history?: CreatorSettingsThreeWayPair | null;
}

export interface CreatorSettingsThreeWayPair {
  pillars: CreatorSettingsDiffPart;
  global_outline: CreatorSettingsDiffPart;
}

export interface CreatorUiProfileSaveRequest {
  creation_mode?: "companion" | "advance" | "studio" | null;
  quality_profile?: string | null;
  advanced_visible?: boolean | null;
  wizard_visible?: boolean | null;
  dashboard_visible?: boolean | null;
}

export interface CreatorUiProfileState {
  creation_mode: "companion" | "advance" | "studio";
  quality_profile: string;
  advanced_visible?: boolean | null;
  wizard_visible?: boolean | null;
  dashboard_visible?: boolean | null;
}

export interface CreatorVolumeApplyTemplateRequest {
  template_id: string;
  max_chapter?: number | null;
}

export interface CreatorVolumeApplyTemplateResponse {
  template_id: string;
  template_name: string;
  volumes: CreatorVolumePlanEntry[];
}

export interface CreatorVolumeDeleteTemplateResponse {
  id: string;
  deleted: boolean;
}

export interface CreatorVolumeDeviation {
  type: string;
  severity: string;
  chapter: number;
  volume_label?: string | null;
  message: string;
}

export interface CreatorVolumeFactoryDeleteResponse {
  id: string;
  deleted: boolean;
}

export interface CreatorVolumeFactoryPublishRequest {
  template_id: string;
}

export interface CreatorVolumeFactoryPublishResponse {
  id: string;
  name: string;
  description: string;
}

export interface CreatorVolumeFactoryPullRequest {
  template_ids: string[];
}

export interface CreatorVolumeFactoryPullResponse {
  imported: number;
  total: number;
  template_ids: string[];
}

export interface CreatorVolumeMergeRequest {
  volumes: CreatorVolumePlanEntry[];
  start_index: number;
  end_index: number;
  label?: string | null;
  core_conflict?: string | null;
}

export interface CreatorVolumeMergeResponse {
  volumes: CreatorVolumePlanEntry[];
  merged_label: string;
  merged_range: string;
}

export interface CreatorVolumePlanDiffChange {
  type: string;
  label: string;
  message: string;
  details?: string[];
}

export interface CreatorVolumePlanDiffResponse {
  has_changes: boolean;
  changes: CreatorVolumePlanDiffChange[];
  global_outline_excerpt?: string;
  global_outline_path?: string;
  highlight_volume_labels?: string[];
  global_outline_lines?: CreatorOutlineHighlightLine[];
}

export interface CreatorVolumePlanEntry {
  label: string;
  start_chapter: number;
  end_chapter: number;
  core_conflict?: string;
  locked?: boolean;
  locked_at?: string | null;
}

export interface CreatorVolumePlanResponse {
  slug: string;
  global_outline_path: string;
  state_path: string;
  revision: string;
  volumes: CreatorVolumePlanEntry[];
  locked_volume_count: number;
  deviations: CreatorVolumeDeviation[];
  deviation_count: number;
  alert_count: number;
}

export interface CreatorVolumePlanSaveRequest {
  volumes: CreatorVolumePlanEntry[];
  expected_revision?: string | null;
}

export interface CreatorVolumeRenameTemplateRequest {
  name: string;
  description?: string | null;
  version_label?: string | null;
}

export interface CreatorVolumeRenameTemplateResponse {
  id: string;
  name: string;
  description: string;
  version_label?: string | null;
}

export interface CreatorVolumeSaveTemplateRequest {
  name: string;
  volumes: CreatorVolumePlanEntry[];
  max_chapter?: number | null;
  description?: string | null;
  version_label?: string | null;
}

export interface CreatorVolumeSaveTemplateResponse {
  id: string;
  name: string;
  description: string;
}

export interface CreatorVolumeSplitRequest {
  volumes: CreatorVolumePlanEntry[];
  volume_index: number;
  split_at_chapter: number;
  first_label?: string | null;
  second_label?: string | null;
}

export interface CreatorVolumeSplitResponse {
  volumes: CreatorVolumePlanEntry[];
  first_label: string;
  second_label: string;
  first_range: string;
  second_range: string;
}

export interface CreatorVolumeSummaryGenerateRequest {
  start_chapter: number;
  end_chapter: number;
}

export interface CreatorVolumeSummaryGenerateResponse {
  path: string;
  written?: boolean;
}

export interface CreatorVolumeTemplateApproval {
  id: string;
  template_id: string;
  scope?: string;
  status?: string;
  version_label?: string | null;
  previous_label?: string | null;
  submitted_at?: string | null;
  resolved_at?: string | null;
  reject_reason?: string;
  submit_note?: string;
  resolve_note?: string;
  current_assignee?: string;
  current_assignees?: string[];
  or_signing?: boolean;
  has_volumes_snapshot?: boolean;
  chain_step?: number;
  chain_total?: number;
  chain_progress?: string;
  chain_log?: Record<string, unknown>[];
  hours_pending?: number | null;
}

export interface CreatorVolumeTemplateApprovalAuditExportResponse {
  schema_version?: string;
  count: number;
  approvals: CreatorVolumeTemplateApproval[];
}

export interface CreatorVolumeTemplateApprovalBatchRequest {
  approval_ids: string[];
  assignee?: string;
  resolve_note?: string;
  reason?: string;
  force?: boolean;
}

export interface CreatorVolumeTemplateApprovalBatchResponse {
  approved?: number;
  rejected?: number;
  total: number;
  results?: CreatorVolumeTemplateApprovalBatchResult[];
}

export interface CreatorVolumeTemplateApprovalBatchResult {
  id: string;
  ok: boolean;
  status?: string | null;
  chain_advanced?: boolean | null;
  error?: string | null;
}

export interface CreatorVolumeTemplateApprovalChainConfig {
  required_steps?: number;
  step_assignees?: string[];
  step_assignee_groups?: string[][] | null;
}

export interface CreatorVolumeTemplateApprovalDriftResponse {
  approval_id: string;
  template_id: string;
  drifted: boolean;
  diff_summary?: Record<string, unknown>;
  force?: boolean;
}

export interface CreatorVolumeTemplateApprovalHistoryResponse {
  approvals: CreatorVolumeTemplateApproval[];
}

export interface CreatorVolumeTemplateApprovalListResponse {
  approvals: CreatorVolumeTemplateApproval[];
}

export interface CreatorVolumeTemplateApprovalOverdueResponse {
  overdue_count: number;
  approvals?: CreatorVolumeTemplateApproval[];
}

export interface CreatorVolumeTemplateApprovalRejectRequest {
  reason?: string;
  resolve_note?: string;
}

export interface CreatorVolumeTemplateApprovalResolveRequest {
  assignee?: string;
  resolve_note?: string;
  force?: boolean;
}

export interface CreatorVolumeTemplateApprovalSlaConfig {
  timeout_hours?: number;
  email_on_submit?: boolean;
  email_on_reject?: boolean;
  email_on_overdue?: boolean;
}

export interface CreatorVolumeTemplateApprovalSnapshotDiffResponse {
  approval_id: string;
  template_id: string;
  has_volumes_snapshot?: boolean;
  diff_summary?: Record<string, unknown>;
  visual_diff?: Record<string, unknown>;
}

export interface CreatorVolumeTemplateApprovalSubmitRequest {
  version_label?: string | null;
  submit_note?: string;
}

export interface CreatorVolumeTemplateApprovalTransferRequest {
  to_assignee: string;
  note?: string;
}

export interface CreatorVolumeTemplateChangelogDiffSummary {
  changed?: boolean;
  lines_added?: number;
  lines_removed?: number;
  snippet?: string[];
}

export interface CreatorVolumeTemplateChangelogEntry {
  version_label?: string | null;
  previous_label?: string | null;
  changed_at?: string | null;
  diff_summary?: CreatorVolumeTemplateChangelogDiffSummary | null;
  visual_diff?: CreatorVolumeTemplateChangelogVisualDiff | null;
  can_rollback?: boolean;
}

export interface CreatorVolumeTemplateChangelogResponse {
  template_id: string;
  entries: CreatorVolumeTemplateChangelogEntry[];
}

export interface CreatorVolumeTemplateChangelogVisualDiff {
  before?: string;
  after?: string;
  lines?: CreatorVolumeTemplateChangelogVisualLine[];
}

export interface CreatorVolumeTemplateChangelogVisualLine {
  type: string;
  text: string;
}

export interface CreatorVolumeTemplateExportResponse {
  schema_version: string;
  templates: Record<string, unknown>[];
  count: number;
}

export interface CreatorVolumeTemplateImportRequest {
  templates: Record<string, unknown>[];
  replace?: boolean;
}

export interface CreatorVolumeTemplateImportResponse {
  imported: number;
  total: number;
  replaced: boolean;
}

export interface CreatorVolumeTemplateInfo {
  id: string;
  name: string;
  description: string;
  builtin?: boolean;
  scope?: string;
  version_label?: string | null;
  version_semver_valid?: boolean;
  version_changelog?: Record<string, unknown>[];
}

export interface CreatorVolumeTemplateListResponse {
  templates: CreatorVolumeTemplateInfo[];
}

export interface CreatorVolumeTemplateRollbackRequest {
  version_label?: string | null;
  changelog_index?: number | null;
}

export interface CreatorVolumeTemplateRollbackResponse {
  id: string;
  version_label?: string | null;
  rolled_back_to?: string | null;
}

export interface CreatorVolumeTemplateSyncRequest {
  source_slugs: string[];
}

export interface CreatorVolumeTemplateSyncResponse {
  imported: number;
  total: number;
  sources: string[];
}

export interface CreatorVolumeTemplateSyncSource {
  slug: string;
  name: string;
  template_count: number;
}

export interface CreatorVolumeTemplateSyncSourcesResponse {
  sources: CreatorVolumeTemplateSyncSource[];
}

export interface CreatorVolumeTemplateVersionRequest {
  version_label?: string | null;
}

export interface CreatorVolumeTemplateVersionResponse {
  id: string;
  version_label?: string | null;
}

export interface CreatorWizardPanelCollapsedRequest {
  collapsed: boolean;
}
