// AUTO-GENERATED by tooling/contracts/generate.py — do not edit.
// Source: packages/lingwen-shared/src/lingwen_shared/contracts/python/creator_sse.py

export interface AdviceEvent {
  type: "advice";
  text: string;
  severity?: "info" | "warning" | "critical" | null;
}

export interface ChunkEvent {
  type: "chunk";
  text: string;
  index?: number | null;
}

export interface CreatorAgentPlanResponse {
  results?: Record<string, unknown>[];
  annotations?: Record<string, unknown>[];
  advice?: string | null;
}

export interface CreatorAgentPlanResult {
  results?: Record<string, unknown>[];
  annotations?: Record<string, unknown>[];
  advice?: string | null;
}

export interface DoneEvent {
  type: "done";
  plan: CreatorAgentPlanResponse;
}

export interface ErrorEvent {
  type: "error";
  message: string;
  code?: string | null;
}

export interface PreviewLabelEvent {
  type: "preview_label";
  label: string;
}

export interface StartEvent {
  type: "start";
  message?: string | null;
}

export interface StatusEvent {
  type: "status";
  message: string;
}
