// AUTO-GENERATED by tooling/contracts/generate.py — do not edit.
// Source: packages/lingwen-shared/src/lingwen_shared/contracts/python/cvg.py

export interface CascadeBroadcastLogResponse {
  id: number;
  ripple_id: string;
  latency_ms: number;
  created_at: string;
}

export interface CascadeCancelPayload {
  run_id: string;
  cancelled_at?: string | null;
  reason?: string | null;
}

export interface CascadeEdgeResponse {
  source: string;
  target: string;
  relation: string;
  weight?: number | null;
}

export interface CascadeNodeResponse {
  node_id: string;
  chapter_id: number;
  title: string;
  status: string;
  depth: number;
}

export interface CascadePreviewResponse {
  ripple_id: string;
  estimated_impact: number;
  affected_chapters?: number[];
  preview_tree?: CascadeResponse | null;
  warnings?: string[] | null;
  affected_chapter_count?: number;
  affected_character_count?: number;
  affected_setting_count?: number;
  estimated_change_count?: number;
  cascade_node_count?: number;
  cascade_edge_count?: number;
  max_depth?: number;
}

export interface CascadeResponse {
  ripple_id: string;
  nodes: CascadeNodeResponse[];
  edges: CascadeEdgeResponse[];
  total_nodes: number;
  total_edges: number;
  max_depth: number;
  status?: string | null;
  cascade_actions?: Record<string, unknown>[];
  generated_at?: string | null;
  bfs_algorithm_version?: "v1" | "v2_weighted";
}

export interface CascadeRunResponse {
  run_id: string;
  ripple_id: string;
  status: string;
  started_at: string;
  finished_at?: string | null;
  nodes_processed: number;
  max_depth: number;
  algorithm?: string | null;
  metadata?: Record<string, unknown> | null;
  cascade_id?: number | null;
  completed_at?: string | null;
  depth_reached?: number;
  cascade_nodes?: CascadeNodeResponse[];
  cascade_edges?: CascadeEdgeResponse[];
  cascade_actions?: Record<string, unknown>[];
  cancelled_at?: string | null;
  triggered_by?: string | null;
  stats?: Record<string, unknown> | null;
}

export interface ReferenceGraphResponse {
  nodes: Record<string, unknown>[];
  edges: Record<string, unknown>[];
  total_nodes: number;
  total_edges: number;
  by_dimension?: Record<string, unknown> | null;
}

export interface RippleActionResponse {
  ripple_id: string;
  action: string;
  status: string;
  applied_at?: string | null;
  rejected_at?: string | null;
  reason?: string | null;
  message?: string | null;
}

export interface RippleAuditEntryResponse {
  audit_id: string;
  ripple_id: string;
  action: string;
  actor: string;
  timestamp: string;
  reason?: string | null;
  metadata?: Record<string, unknown> | null;
}

export interface RippleDetailResponse {
  ripple_id: string;
  chapter_id: number;
  title: string;
  status: string;
  source_volume: number;
  impact_volumes?: number[];
  created_at: string;
  updated_at?: string | null;
  proposed_by?: string | null;
  applies_count?: number | null;
  impact_score?: number | null;
  description?: string | null;
  evidence?: Record<string, unknown> | null;
  references?: Record<string, unknown>[] | null;
  apply_metadata?: Record<string, unknown> | null;
  audit_trail?: RippleAuditEntryResponse[] | null;
}

export interface RippleListItemResponse {
  ripple_id: string;
  chapter_id: number;
  title: string;
  status: string;
  source_volume: number;
  impact_volumes?: number[];
  created_at: string;
  updated_at?: string | null;
  proposed_by?: string | null;
  applies_count?: number | null;
  impact_score?: number | null;
}

export interface RippleStatsResponse {
  total: number;
  pending: number;
  applied: number;
  rejected: number;
  rolled_back: number;
  by_status?: Record<string, unknown> | null;
  by_volume?: Record<string, unknown> | null;
}
