// AUTO-GENERATED by tooling/contracts/generate.py — do not edit.
// Source: packages/lingwen-shared/src/lingwen_shared/contracts/python/decisions.py

export interface CancelDecisionRequest {
  reason?: string;
}

export interface DecisionResponse {
  decision_id: string;
  kind: string;
  node_id: string;
  prompt: string;
  options: string[];
  priority: number;
  status: string;
  context?: Record<string, unknown>;
  created_at?: string | null;
  resolution?: string | null;
  resolved_at?: string | null;
  resolved_by?: string | null;
  reason?: string | null;
}

export interface DeferDecisionRequest {
  reason?: string;
}

export interface ResolveDecisionRequest {
  option: string;
  resolved_by?: string;
}
