// AUTO-GENERATED by tooling/contracts/generate.py — do not edit.
// Source: packages/lingwen-shared/src/lingwen_shared/contracts/python/health.py

export interface ChapterData {
  chapter: number;
  hook_count: number;
  hook_strength_avg: number;
  coolpoint_count: number;
  coolpoint_density: number;
}

export interface ChaptersResponse {
  chapters: ChapterData[];
}

export interface DatabaseStatus {
  status: string;
  error?: string | null;
  tables?: number | null;
  records?: number | null;
}

export interface HealthResponse {
  status: string;
  service: string;
  timestamp: string;
  uptime: number;
  version: string;
  python_version: string;
  database: DatabaseStatus;
  memory: MemoryUsage;
  environment?: string | null;
  features?: Record<string, unknown> | null;
}

export interface MemoryUsage {
  rss_mb: number;
  vms_mb: number;
  cpu_percent: number;
  num_threads: number;
}

export interface OverviewResponse {
  total_chapters: number;
  total_hooks: number;
  avg_hook_strength: number;
  total_coolpoints: number;
  avg_coolpoint_density: number;
}

export interface ProductionBatchRollupResponse {
  record_id: string;
  chapter_range?: string | null;
  total_cost_usd?: number | null;
  stopped_reason?: string | null;
  recorded_at?: string | null;
  source_file: string;
}

export interface ProductionCostTrendPointResponse {
  recorded_at?: string | null;
  record_id: string;
  record_type: string;
  label: string;
  cost_usd?: number | null;
  incremental_cost_usd: number;
  cumulative_cost_usd: number;
}

export interface ProductionCostTrendResponse {
  records_dir: string;
  point_count: number;
  total_cost_usd: number;
  points: ProductionCostTrendPointResponse[];
}

export interface ProductionRecordResponse {
  record_id: string;
  record_type: string;
  chapter_num?: number | null;
  chapter_range?: string | null;
  operator?: string | null;
  recorded_at?: string | null;
  provider?: string | null;
  total_cost_usd?: number | null;
  emit_chapter_completed?: boolean | null;
  memory_context_source?: string | null;
  stopped_reason?: string | null;
  source_file: string;
}

export interface ProductionRecordsResponse {
  records_dir: string;
  records: ProductionRecordResponse[];
}

export interface ProductionRollupResponse {
  records_dir: string;
  record_count: number;
  pilot_count: number;
  batch_count: number;
  total_cost_usd: number;
  chapters_with_records: number;
  latest_recorded_at?: string | null;
  batches: ProductionBatchRollupResponse[];
}
