// AUTO-GENERATED by tooling/contracts/generate.py — do not edit.
// Source: packages/lingwen-shared/src/lingwen_shared/contracts/python/quality.py

export interface ProseDiffDTO {
  chapter_id: string;
  base_revision: number;
  head_revision: number;
  additions?: number;
  deletions?: number;
  diff_summary?: string | null;
}

export interface ProseJudgeDTO {
  chapter_id: string;
  verdict: "pass" | "revise" | "rewrite";
  rationale: string;
  score: number;
  issues?: string[] | null;
}

export interface QualityScoreDTO {
  chapter_id?: string | null;
  overall_score: number;
  dimensions: Record<string, unknown>;
  computed_at?: string | null;
  model?: string | null;
}
