// AUTO-GENERATED by tooling/contracts/generate.py — do not edit.
// Source: packages/lingwen-shared/src/lingwen_shared/contracts/python/studio.py

export interface StudioActiveResponse {
  slug: string;
  name: string;
  root: string;
  role: string;
}

export interface StudioBatchJobResponse {
  job_id: string;
  slug: string;
  start_chapter: number;
  end_chapter: number;
  budget_usd: number;
  mode: string;
  status: string;
  pid?: number | null;
  log_path: string;
  started_at: string;
  finished_at?: string | null;
  exit_code?: number | null;
  error?: string | null;
  log_tail?: string | null;
}

export interface StudioBatchRunRequest {
  start_chapter: number;
  end_chapter: number;
  mode?: string;
  budget_usd?: number;
  skip_preflight?: boolean;
}

export interface StudioPreflightChapter {
  chapter: number;
  ok: boolean;
  message: string;
}

export interface StudioPreflightRequest {
  start_chapter: number;
  end_chapter: number;
  mode?: string | null;
}

export interface StudioPreflightResponse {
  slug: string;
  mode: string;
  start_chapter: number;
  end_chapter: number;
  all_ok: boolean;
  chapters: StudioPreflightChapter[];
  batch_command: string;
}

export interface StudioProjectItem {
  slug: string;
  name: string;
  role: string;
  root: string;
  location: string;
}

export interface StudioProjectsResponse {
  projects: StudioProjectItem[];
  active_slug?: string | null;
}

export interface StudioProseDiffChapter {
  chapter: number;
  before_prose_p1: number;
  after_prose_p1: number;
  delta_prose_p1: number;
  before_prose_total: number;
  after_prose_total: number;
  delta_prose_total: number;
}

export interface StudioProseDiffResponse {
  slug: string;
  available: boolean;
  reason?: string | null;
  snapshot_path?: string | null;
  report_path?: string | null;
  save_command?: string | null;
  before_captured_at?: string | null;
  after_captured_at?: string | null;
  total_delta?: StudioProseDiffTotals | null;
  chapters?: StudioProseDiffChapter[];
  improved_count?: number;
  regressed_count?: number;
  has_regression?: boolean;
  net_prose_p1_delta?: number;
}

export interface StudioProseDiffTotals {
  p0?: number;
  p1?: number;
  total?: number;
  prose_p1?: number;
  prose_total?: number;
}

export interface StudioProseHeatmap {
  chapters: StudioProseHeatmapChapter[];
  max_prose_per_chapter?: number | null;
  total_prose_issues?: number | null;
  total_prose_p1?: number | null;
}

export interface StudioProseHeatmapChapter {
  chapter: number;
  issue_count: number;
  prose_p1: number;
  prose_total: number;
  structural_total: number;
  heat: number;
}

export interface StudioProseJudgeChapter {
  chapter: number;
  avg_score: number;
  ratings: StudioProseJudgeRating[];
}

export interface StudioProseJudgeRating {
  dimension: string;
  score: number;
  evidence: string;
  action: string;
}

export interface StudioProseJudgeResponse {
  slug: string;
  available: boolean;
  reason?: string | null;
  report_path?: string | null;
  generate_command?: string | null;
  source?: string | null;
  judged_at?: string | null;
  golden_chapters?: number[];
  weighted_avg?: number;
  chapters?: StudioProseJudgeChapter[];
  high_priority_count?: number;
  false_positive_candidate_count?: number;
  review_needed_count?: number;
  high_priority?: StudioProseJudgeSignal[];
  false_positive_candidates?: StudioProseJudgeSignal[];
  review_needed?: StudioProseJudgeSignal[];
}

export interface StudioProseJudgeSignal {
  chapter: number;
  issue_type?: string | null;
  dimension?: string | null;
  judge_score: number;
  description?: string | null;
  evidence?: string | null;
}

export interface StudioQualityReportChapter {
  chapter: number;
  word_count: number;
  issue_count: number;
  issues: StudioQualityReportIssue[];
}

export interface StudioQualityReportIssue {
  severity: string;
  issue_type: string;
  chapter: number;
  description: string;
}

export interface StudioQualityReportResponse {
  slug: string;
  available: boolean;
  path: string;
  total: number;
  p0: number;
  p1: number;
  p2: number;
  p3: number;
  generated_at?: string | null;
  chapters: StudioQualityReportChapter[];
  prose_heatmap: StudioProseHeatmap;
}

export interface StudioQualityResponse {
  slug: string;
  pillars_ok: boolean;
  pillars_path: string;
  require_chapter_outline: boolean;
  max_chapter: number;
  chapters_written: number;
  outlines_present: number;
  coverage_pct: number;
  missing_outlines: number[];
  missing_bodies: number[];
  golden_set_status: string;
  golden_regression_cmd: string;
}

export interface StudioSetActiveRequest {
  slug: string;
}

export interface StudioSummaryResponse {
  slug: string;
  name: string;
  role: string;
  root: string;
  location: string;
  max_chapter: number;
  genre: string;
  chapter_count: number;
  latest_chapter: number;
  outline_count: number;
  golden_chapters: number[];
  has_golden_set: boolean;
  pilot_records_dir: string;
  pilot_record_count: number;
  pillars_ok: boolean;
  pillars_path: string;
  creation_mode?: string;
  quality_profile?: string;
}
