// AUTO-GENERATED by tooling/contracts/generate.py — do not edit.
// Source: packages/lingwen-shared/src/lingwen_shared/contracts/python/workspace.py

export interface AnnotationDTO {
  id: string;
  scene_id: string;
  kind: "comment" | "highlight" | "revision_note";
  body: string;
  author?: string | null;
  created_at?: string | null;
}

export interface ChapterDTO {
  id?: number | null;
  project_slug: string;
  chapter_number: number;
  title: string;
  content: string;
  word_count?: number;
  last_modified?: string | null;
}

export interface ConflictDTO {
  chapter_id: number;
  base_revision: number;
  head_revision: number;
  conflicting_content: string;
  resolution_hint?: string | null;
}

export interface SceneDTO {
  id: string;
  chapter_id: number;
  order: number;
  content: string;
  word_count?: number;
}
