// AUTO-GENERATED by tooling/contracts/generate.py — do not edit.
// Source: packages/lingwen-shared/src/lingwen_shared/contracts/python/workflows.py

export interface ResumeWorkflowRequest {
  decision_id: string;
  option: string;
  resolved_by?: string;
  cost_budget_usd?: number | null;
}

export interface RunWorkflowRequest {
  workflow_name: string;
  initial_inputs?: Record<string, unknown> | null;
  start_nodes?: string[] | null;
  max_backtracks?: number;
  base_dir?: string | null;
  cost_budget_usd?: number | null;
}

export interface WorkflowListItem {
  name: string;
  path: string;
  node_count: number;
  has_decision_nodes: boolean;
}

export interface WorkflowMermaidResponse {
  workflow_name: string;
  mermaid: string;
  node_count: number;
  has_decision_nodes: boolean;
  status_applied?: boolean;
  node_statuses?: Record<string, unknown>;
}

export interface WorkflowStatusResponse {
  workflow_name?: string | null;
  is_active?: boolean | null;
  completed?: number | null;
  failed?: number | null;
  paused?: boolean | null;
  paused_nodes?: string[] | null;
  node_count?: number | null;
  steps?: number | null;
  total_cost_usd?: number | null;
  pending_decisions?: Record<string, unknown>[] | null;
  executions?: Record<string, unknown> | null;
  score_data?: Record<string, unknown> | null;
  cost_by_scenario?: Record<string, unknown> | null;
  cost_by_tier?: Record<string, unknown> | null;
  cost_by_day?: Record<string, unknown> | null;
  cost_by_day_per_tier?: Record<string, unknown> | null;
  cost_budget_status?: Record<string, unknown> | null;
  budget_per_day?: Record<string, unknown> | null;
  budget_per_week?: Record<string, unknown> | null;
  budget_by_tier?: Record<string, unknown> | null;
  incremental_backfill?: Record<string, unknown> | null;
  production_summary?: Record<string, unknown> | null;
}
