// AUTO-GENERATED by tooling/contracts/generate.py — do not edit.
// Source: packages/lingwen-shared/src/lingwen_shared/contracts/python/world.py

export interface CharacterDTO {
  id: number;
  slug: string;
  name: string;
  canon_level: "Draft" | "Secondary" | "Primary";
  status?: string | null;
  first_chapter?: number | null;
  last_seen_chapter?: number | null;
  attributes?: Record<string, unknown> | null;
  aliases?: string[] | null;
  notes?: string | null;
}

export interface CharacterUpdatePayload {
  name?: string | null;
  canon_level?: "Draft" | "Secondary" | "Primary" | null;
  status?: string | null;
  first_chapter?: number | null;
  last_seen_chapter?: number | null;
  attributes?: Record<string, unknown> | null;
  aliases?: string[] | null;
  notes?: string | null;
}

export interface FactionDTO {
  id: number;
  slug: string;
  name: string;
  description?: string | null;
  canon_level?: "Draft" | "Secondary" | "Primary";
}

export interface LoreDTO {
  id: number;
  category: string;
  title: string;
  body: string;
  canon_level?: "Draft" | "Secondary" | "Primary";
}

export interface ProposalDTO {
  id?: number | null;
  kind: "character.update" | "character.create";
  target_kind?: "character" | "faction" | null;
  target_id?: number;
  payload: CharacterUpdatePayload;
  source?: string;
  source_context?: string | null;
  confidence?: "high" | "medium" | "low";
  status?: "pending" | "accepted" | "rejected" | "applied";
}

export interface TimelineEventDTO {
  id: number;
  project_slug: string;
  chapter_number: number;
  title: string;
  description?: string | null;
  characters_involved?: number[] | null;
  canon_level?: "Draft" | "Secondary" | "Primary";
}
