"""Contract regression tests for CreatorAgentStreamEvent discriminated union.

Phase 126 v16.5 #N.10: status event promoted from defensive extension to
canonical variant. Canonical source-of-truth is
``packages/lingwen-shared/src/lingwen_shared/contracts/python/creator_sse.py``;
TS is auto-generated by ``tooling/contracts/generate.py``.
"""
from __future__ import annotations

import pytest
from pydantic import ValidationError


def test_creator_sse_models_importable() -> None:
    """All CreatorAgentStreamEvent variants must import from creator_sse module."""
    from lingwen_shared.contracts.python.creator_sse import (  # noqa: F401
        AdviceEvent,
        ChunkEvent,
        CreatorAgentPlanResult,
        CreatorAgentStreamEvent,
        DoneEvent,
        ErrorEvent,
        PreviewLabelEvent,
        StartEvent,
        StatusEvent,
    )


def test_creator_agent_stream_event_status_variant_is_canonical() -> None:
    """CreatorAgentStreamEvent must accept a 'status' variant with 'message' field.

    Phase 126 v16.5 #N.10: backend SSE emits ``{"type": "status", "message": "..."}``
    events (see packages/lingwen-creator/src/lingwen_creator/content/agent.py:534/537/592).
    Promoting status from a defensive local extension in
    apps/dashboard/src/composables/useCreatorAgent/useAgentTask.ts to a canonical
    Pydantic variant closes the type-contract gap.
    """
    from lingwen_shared.contracts.python.creator_sse import CreatorAgentStreamEvent

    event = CreatorAgentStreamEvent.model_validate({
        "type": "status",
        "message": "正在分析写作范围…",
    })
    assert event.type == "status"
    assert event.message == "正在分析写作范围…"


def test_creator_agent_stream_event_chunk_variant_still_works() -> None:
    """Existing 'chunk' variant must continue to validate (no regression)."""
    from lingwen_shared.contracts.python.creator_sse import CreatorAgentStreamEvent

    event = CreatorAgentStreamEvent.model_validate({"type": "chunk", "text": "hello"})
    assert event.type == "chunk"
    assert event.text == "hello"


def test_creator_agent_stream_event_unknown_type_rejected() -> None:
    """Unknown event types must be rejected (strict discriminated union).

    Pydantic v2's tagged-union validator (``discriminator='type'``) raises
    ValidationError on variants not in the union, surfacing backend-vs-frontend
    drift early instead of silently passing through.
    """
    from lingwen_shared.contracts.python.creator_sse import CreatorAgentStreamEvent

    with pytest.raises(ValidationError):
        CreatorAgentStreamEvent.model_validate({"type": "unknown_event_type"})


def test_status_event_module_construction() -> None:
    """StatusEvent module-level construction (used in tests + adapter code)."""
    from lingwen_shared.contracts.python.creator_sse import StatusEvent

    event = StatusEvent(type="status", message="正在生成候选…")
    assert event.type == "status"
    assert event.message == "正在生成候选…"


def test_status_event_message_required() -> None:
    """StatusEvent must require 'message' (no optional default — status without message is meaningless)."""
    from lingwen_shared.contracts.python.creator_sse import StatusEvent

    with pytest.raises(ValidationError):
        StatusEvent(type="status")
