"""Pydantic v2 DTOs for the creator bounded context — Volume domain.

Source of truth: lingwen_shared.contracts.python.creator (this file).
TypeScript types are auto-generated by tooling/contracts/generate.py.

Phase 126 v16.2.1 Task 3.2: Volume DTOs (~50 DTOs covering plan, merge/split,
diff, templates, template approvals, factory sync, summary).

Each DTO mirrors the corresponding Pydantic model in
``apps/studio_api/models/`` (creator.py, creator_overview.py,
creator_volume_op.py, creator_template.py, creator_settings.py) so the
backend routes can re-export from this module without behavior change.

Conventions (v16.1 lessons):
- All DTOs use ``model_config = ConfigDict(extra="ignore")`` (forward compat).
- Optional fields use ``Optional[T] = None`` defaults.
- Self-referencing types resolve via ``from __future__ import annotations``.
"""
from __future__ import annotations

from typing import Any, Optional

from pydantic import BaseModel, ConfigDict

# ---------------------------------------------------------------------------
# Plan core
# ---------------------------------------------------------------------------


class CreatorVolumePlanEntry(BaseModel):
    """Single volume plan row (label + chapter range + lock metadata)."""

    model_config = ConfigDict(extra="ignore")

    label: str
    start_chapter: int
    end_chapter: int
    core_conflict: str = ""
    locked: bool = False
    locked_at: Optional[str] = None


class CreatorVolumeDeviation(BaseModel):
    """Deviation row surfaced in plan response."""

    model_config = ConfigDict(extra="ignore")

    type: str
    severity: str
    chapter: int
    volume_label: Optional[str] = None
    message: str


class CreatorVolumePlanResponse(BaseModel):
    """Response shape for ``GET /api/creator/volume-plan``."""

    model_config = ConfigDict(extra="ignore")

    slug: str
    global_outline_path: str
    state_path: str
    revision: str
    volumes: list[CreatorVolumePlanEntry]
    locked_volume_count: int
    deviations: list[CreatorVolumeDeviation]
    deviation_count: int
    alert_count: int


class CreatorVolumePlanSaveRequest(BaseModel):
    """Request body for ``PUT /api/creator/volume-plan``."""

    model_config = ConfigDict(extra="ignore")

    volumes: list[CreatorVolumePlanEntry]
    expected_revision: Optional[str] = None


class CreatorVolumePlanDiffChange(BaseModel):
    """Single change entry in the volume plan diff payload."""

    model_config = ConfigDict(extra="ignore")

    type: str
    label: str
    message: str
    details: list[str] = []


class CreatorOutlineHighlightLine(BaseModel):
    """One outline line used by the diff side-by-side viewer."""

    model_config = ConfigDict(extra="ignore")

    text: str
    highlighted: bool = False


class CreatorVolumePlanDiffResponse(BaseModel):
    """Response shape for ``POST /api/creator/volume-plan/diff``."""

    model_config = ConfigDict(extra="ignore")

    has_changes: bool
    changes: list[CreatorVolumePlanDiffChange]
    global_outline_excerpt: str = ""
    global_outline_path: str = ""
    highlight_volume_labels: list[str] = []
    global_outline_lines: list[CreatorOutlineHighlightLine] = []


# ---------------------------------------------------------------------------
# Merge / split operations
# ---------------------------------------------------------------------------


class CreatorVolumeMergeRequest(BaseModel):
    """Request body for ``POST /api/creator/volume-plan/merge``."""

    model_config = ConfigDict(extra="ignore")

    volumes: list[CreatorVolumePlanEntry]
    start_index: int
    end_index: int
    label: Optional[str] = None
    core_conflict: Optional[str] = None


class CreatorVolumeMergeResponse(BaseModel):
    """Response shape for merge endpoint."""

    model_config = ConfigDict(extra="ignore")

    volumes: list[CreatorVolumePlanEntry]
    merged_label: str
    merged_range: str


class CreatorVolumeSplitRequest(BaseModel):
    """Request body for ``POST /api/creator/volume-plan/split``."""

    model_config = ConfigDict(extra="ignore")

    volumes: list[CreatorVolumePlanEntry]
    volume_index: int
    split_at_chapter: int
    first_label: Optional[str] = None
    second_label: Optional[str] = None


class CreatorVolumeSplitResponse(BaseModel):
    """Response shape for split endpoint."""

    model_config = ConfigDict(extra="ignore")

    volumes: list[CreatorVolumePlanEntry]
    first_label: str
    second_label: str
    first_range: str
    second_range: str


# ---------------------------------------------------------------------------
# Templates — info / list / changelog / version
# ---------------------------------------------------------------------------


class CreatorVolumeTemplateInfo(BaseModel):
    """Single volume template row (custom or factory)."""

    model_config = ConfigDict(extra="ignore")

    id: str
    name: str
    description: str
    builtin: bool = True
    scope: str = "builtin"
    version_label: Optional[str] = None
    version_semver_valid: bool = True
    version_changelog: list[dict[str, Any]] = []


class CreatorVolumeTemplateListResponse(BaseModel):
    """List of volume templates."""

    model_config = ConfigDict(extra="ignore")

    templates: list[CreatorVolumeTemplateInfo]


class CreatorVolumeTemplateChangelogDiffSummary(BaseModel):
    """Aggregated diff counters for a changelog entry."""

    model_config = ConfigDict(extra="ignore")

    changed: bool = False
    lines_added: int = 0
    lines_removed: int = 0
    snippet: list[str] = []


class CreatorVolumeTemplateChangelogVisualLine(BaseModel):
    """Visual diff line marker."""

    model_config = ConfigDict(extra="ignore")

    type: str
    text: str


class CreatorVolumeTemplateChangelogVisualDiff(BaseModel):
    """Visual before/after block for a changelog entry."""

    model_config = ConfigDict(extra="ignore")

    before: str = ""
    after: str = ""
    lines: list[CreatorVolumeTemplateChangelogVisualLine] = []


class CreatorVolumeTemplateChangelogEntry(BaseModel):
    """One changelog entry for a template version."""

    model_config = ConfigDict(extra="ignore")

    version_label: Optional[str] = None
    previous_label: Optional[str] = None
    changed_at: Optional[str] = None
    diff_summary: Optional[CreatorVolumeTemplateChangelogDiffSummary] = None
    visual_diff: Optional[CreatorVolumeTemplateChangelogVisualDiff] = None
    can_rollback: bool = False


class CreatorVolumeTemplateChangelogResponse(BaseModel):
    """Full changelog payload for a template."""

    model_config = ConfigDict(extra="ignore")

    template_id: str
    entries: list[CreatorVolumeTemplateChangelogEntry]


class CreatorVolumeTemplateRollbackRequest(BaseModel):
    """Request to roll back a template to a previous version."""

    model_config = ConfigDict(extra="ignore")

    version_label: Optional[str] = None
    changelog_index: Optional[int] = None


class CreatorVolumeTemplateRollbackResponse(BaseModel):
    """Response from a rollback operation."""

    model_config = ConfigDict(extra="ignore")

    id: str
    version_label: Optional[str] = None
    rolled_back_to: Optional[str] = None


class CreatorVolumeTemplateVersionRequest(BaseModel):
    """Request to set the version label on a template."""

    model_config = ConfigDict(extra="ignore")

    version_label: Optional[str] = None


class CreatorVolumeTemplateVersionResponse(BaseModel):
    """Response from a version-label update."""

    model_config = ConfigDict(extra="ignore")

    id: str
    version_label: Optional[str] = None


# ---------------------------------------------------------------------------
# Templates — save / rename / delete
# ---------------------------------------------------------------------------


class CreatorVolumeSaveTemplateRequest(BaseModel):
    """Request to save a custom template."""

    model_config = ConfigDict(extra="ignore")

    name: str
    volumes: list[CreatorVolumePlanEntry]
    max_chapter: Optional[int] = None
    description: Optional[str] = None
    version_label: Optional[str] = None


class CreatorVolumeSaveTemplateResponse(BaseModel):
    """Response after saving a custom template."""

    model_config = ConfigDict(extra="ignore")

    id: str
    name: str
    description: str


class CreatorVolumeDeleteTemplateResponse(BaseModel):
    """Response from deleting a custom template."""

    model_config = ConfigDict(extra="ignore")

    id: str
    deleted: bool


class CreatorVolumeRenameTemplateRequest(BaseModel):
    """Request to rename a custom template."""

    model_config = ConfigDict(extra="ignore")

    name: str
    description: Optional[str] = None
    version_label: Optional[str] = None


class CreatorVolumeRenameTemplateResponse(BaseModel):
    """Response from renaming a custom template."""

    model_config = ConfigDict(extra="ignore")

    id: str
    name: str
    description: str
    version_label: Optional[str] = None


# ---------------------------------------------------------------------------
# Templates — export / import / sync
# ---------------------------------------------------------------------------


class CreatorVolumeTemplateExportResponse(BaseModel):
    """Bundle of custom templates for export."""

    model_config = ConfigDict(extra="ignore")

    schema_version: str
    templates: list[dict[str, Any]]
    count: int


class CreatorVolumeTemplateImportRequest(BaseModel):
    """Request body for importing custom templates."""

    model_config = ConfigDict(extra="ignore")

    templates: list[dict[str, Any]]
    replace: bool = False


class CreatorVolumeTemplateImportResponse(BaseModel):
    """Response after importing custom templates."""

    model_config = ConfigDict(extra="ignore")

    imported: int
    total: int
    replaced: bool


class CreatorVolumeTemplateSyncSource(BaseModel):
    """A single project source available for template sync."""

    model_config = ConfigDict(extra="ignore")

    slug: str
    name: str
    template_count: int


class CreatorVolumeTemplateSyncSourcesResponse(BaseModel):
    """List of syncable projects (excluding current)."""

    model_config = ConfigDict(extra="ignore")

    sources: list[CreatorVolumeTemplateSyncSource]


class CreatorVolumeTemplateSyncRequest(BaseModel):
    """Request body for syncing templates from peer projects."""

    model_config = ConfigDict(extra="ignore")

    source_slugs: list[str]


class CreatorVolumeTemplateSyncResponse(BaseModel):
    """Response after syncing custom templates from peers."""

    model_config = ConfigDict(extra="ignore")

    imported: int
    total: int
    sources: list[str]


# ---------------------------------------------------------------------------
# Templates — apply-template (the main entry point for building a plan)
# ---------------------------------------------------------------------------


class CreatorVolumeApplyTemplateRequest(BaseModel):
    """Request to build a volume plan from a template."""

    model_config = ConfigDict(extra="ignore")

    template_id: str
    max_chapter: Optional[int] = None


class CreatorVolumeApplyTemplateResponse(BaseModel):
    """Built plan + template metadata after apply."""

    model_config = ConfigDict(extra="ignore")

    template_id: str
    template_name: str
    volumes: list[CreatorVolumePlanEntry]


# ---------------------------------------------------------------------------
# Factory templates (publish / pull / delete)
# ---------------------------------------------------------------------------


class CreatorVolumeFactoryPublishRequest(BaseModel):
    """Request to publish a custom template to the factory library."""

    model_config = ConfigDict(extra="ignore")

    template_id: str


class CreatorVolumeFactoryPublishResponse(BaseModel):
    """Response after publishing to the factory library."""

    model_config = ConfigDict(extra="ignore")

    id: str
    name: str
    description: str


class CreatorVolumeFactoryPullRequest(BaseModel):
    """Request to pull factory templates into the project."""

    model_config = ConfigDict(extra="ignore")

    template_ids: list[str]


class CreatorVolumeFactoryPullResponse(BaseModel):
    """Response after pulling factory templates."""

    model_config = ConfigDict(extra="ignore")

    imported: int
    total: int
    template_ids: list[str]


class CreatorVolumeFactoryDeleteResponse(BaseModel):
    """Response after deleting a factory template."""

    model_config = ConfigDict(extra="ignore")

    id: str
    deleted: bool


# ---------------------------------------------------------------------------
# Template approvals — request shapes
# ---------------------------------------------------------------------------


class CreatorVolumeTemplateApprovalSubmitRequest(BaseModel):
    """Submit a template version for approval review."""

    model_config = ConfigDict(extra="ignore")

    version_label: Optional[str] = None
    submit_note: str = ""


class CreatorVolumeTemplateApprovalResolveRequest(BaseModel):
    """Generic approve-side request (assignee + resolve note + force flag)."""

    model_config = ConfigDict(extra="ignore")

    assignee: str = ""
    resolve_note: str = ""
    force: bool = False


class CreatorVolumeTemplateApprovalRejectRequest(BaseModel):
    """Reject a template approval."""

    model_config = ConfigDict(extra="ignore")

    reason: str = ""
    resolve_note: str = ""


class CreatorVolumeTemplateApprovalTransferRequest(BaseModel):
    """Transfer a template approval to another assignee."""

    model_config = ConfigDict(extra="ignore")

    to_assignee: str
    note: str = ""


class CreatorVolumeTemplateApprovalBatchRequest(BaseModel):
    """Batch approve/reject a set of template approvals."""

    model_config = ConfigDict(extra="ignore")

    approval_ids: list[str]
    assignee: str = ""
    resolve_note: str = ""
    reason: str = ""
    force: bool = False


# ---------------------------------------------------------------------------
# Template approvals — result / response shapes
# ---------------------------------------------------------------------------


class CreatorVolumeTemplateApprovalBatchResult(BaseModel):
    """Per-item result of a batch approve/reject call."""

    model_config = ConfigDict(extra="ignore")

    id: str
    ok: bool
    status: Optional[str] = None
    chain_advanced: Optional[bool] = None
    error: Optional[str] = None


class CreatorVolumeTemplateApprovalBatchResponse(BaseModel):
    """Aggregate result of a batch approve/reject call."""

    model_config = ConfigDict(extra="ignore")

    approved: int = 0
    rejected: int = 0
    total: int
    results: list[CreatorVolumeTemplateApprovalBatchResult] = []


class CreatorVolumeTemplateApprovalDriftResponse(BaseModel):
    """Result of a snapshot-drift check on a saved approval."""

    model_config = ConfigDict(extra="ignore")

    approval_id: str
    template_id: str
    drifted: bool
    diff_summary: dict[str, Any] = {}
    force: bool = False


class CreatorVolumeTemplateApprovalSnapshotDiffResponse(BaseModel):
    """Snapshot diff preview between current template and the approved version."""

    model_config = ConfigDict(extra="ignore")

    approval_id: str
    template_id: str
    has_volumes_snapshot: bool = False
    diff_summary: dict[str, Any] = {}
    visual_diff: dict[str, Any] = {}


class CreatorVolumeTemplateApprovalOverdueResponse(BaseModel):
    """List of template approvals that have exceeded their SLA."""

    model_config = ConfigDict(extra="ignore")

    overdue_count: int
    approvals: list["CreatorVolumeTemplateApproval"] = []


class CreatorVolumeTemplateApprovalListResponse(BaseModel):
    """Filtered list of template approvals."""

    model_config = ConfigDict(extra="ignore")

    approvals: list["CreatorVolumeTemplateApproval"]


class CreatorVolumeTemplateApprovalHistoryResponse(BaseModel):
    """Most-recent template approval history."""

    model_config = ConfigDict(extra="ignore")

    approvals: list["CreatorVolumeTemplateApproval"]


class CreatorVolumeTemplateApprovalAuditExportResponse(BaseModel):
    """Schema-versioned audit export bundle."""

    model_config = ConfigDict(extra="ignore")

    schema_version: str = "1"
    count: int
    approvals: list["CreatorVolumeTemplateApproval"]


# ---------------------------------------------------------------------------
# Template approvals — config shapes
# ---------------------------------------------------------------------------


class CreatorVolumeTemplateApprovalChainConfig(BaseModel):
    """Chain configuration for template approvals."""

    model_config = ConfigDict(extra="ignore")

    required_steps: int = 2
    step_assignees: list[str] = []
    step_assignee_groups: Optional[list[list[str]]] = None


class CreatorVolumeTemplateApprovalSlaConfig(BaseModel):
    """SLA configuration for template approvals."""

    model_config = ConfigDict(extra="ignore")

    timeout_hours: int = 72
    email_on_submit: bool = True
    email_on_reject: bool = True
    email_on_overdue: bool = True


# ---------------------------------------------------------------------------
# Template approvals — row shape
# (declared last because other DTOs reference it via forward string)
# ---------------------------------------------------------------------------


class CreatorVolumeTemplateApproval(BaseModel):
    """One template approval row."""

    model_config = ConfigDict(extra="ignore")

    id: str
    template_id: str
    scope: str = "custom"
    status: str = "pending"
    version_label: Optional[str] = None
    previous_label: Optional[str] = None
    submitted_at: Optional[str] = None
    resolved_at: Optional[str] = None
    reject_reason: str = ""
    submit_note: str = ""
    resolve_note: str = ""
    current_assignee: str = ""
    current_assignees: list[str] = []
    or_signing: bool = False
    has_volumes_snapshot: bool = False
    chain_step: int = 1
    chain_total: int = 1
    chain_progress: str = "1/1"
    chain_log: list[dict[str, Any]] = []
    hours_pending: Optional[float] = None


# Rebuild forward references now that CreatorVolumeTemplateApproval exists.
# (Pydantic v2 requires explicit rebuild when using string annotations.)
CreatorVolumeTemplateApprovalOverdueResponse.model_rebuild()
CreatorVolumeTemplateApprovalListResponse.model_rebuild()
CreatorVolumeTemplateApprovalHistoryResponse.model_rebuild()
CreatorVolumeTemplateApprovalAuditExportResponse.model_rebuild()


# ---------------------------------------------------------------------------
# Volume summary (generate endpoint)
# ---------------------------------------------------------------------------


class CreatorVolumeSummaryGenerateRequest(BaseModel):
    """Request to generate a markdown volume summary for a chapter range."""

    model_config = ConfigDict(extra="ignore")

    start_chapter: int
    end_chapter: int


class CreatorVolumeSummaryGenerateResponse(BaseModel):
    """Response after generating a volume summary."""

    model_config = ConfigDict(extra="ignore")

    path: str
    written: bool = True
