"""Pydantic v2 DTOs for the creator-agent SSE stream envelope.

Source of truth: ``lingwen_shared.contracts.python.creator_sse`` (this file).
TypeScript types are auto-generated by ``tooling/contracts/generate.py``.

Phase 126 v16.5 #N.7: typed envelope for the ``/creator/agent/plan/stream``
SSE endpoint (see ``apps/studio_api/routes/creator_core.py``
``run_creator_agent_plan_stream``). Each variant is a separate ``BaseModel``
class so Pydantic v2 can validate strict event types and reject unknown types
at parse time.

Phase 126 v16.5 #N.10: ``StatusEvent`` promoted from a defensive local
extension in ``apps/dashboard/src/composables/useCreatorAgent/useAgentTask.ts``
to a canonical variant. Backend SSE emits ``status`` events at 3 points in
``packages/lingwen-creator/src/lingwen_creator/content/agent.py`` (lines
534, 537, 592) — e.g. ``{"type": "status", "message": "正在分析写作范围…"}``.

Conventions (matching v16.1 lessons):
- All DTOs use ``model_config = ConfigDict(extra="ignore")`` (forward compat).
- Optional fields use ``Optional[T] = None`` defaults.
- Tagged union discriminator is ``type`` (Literal per variant).
"""

from __future__ import annotations

from typing import Any, Literal, Optional

from pydantic import BaseModel, ConfigDict, model_validator

from lingwen_shared.contracts.python.creator import CreatorAgentPlanResponse

# ---------------------------------------------------------------------------
# Event variants (each is a Pydantic BaseModel subclass).
#
# Note: variant classes use single-Literal ``type`` field so the discriminated
# union can route on it. ``extra="ignore"`` keeps SSE payloads with optional
# fields forward-compatible (backend may add new optional fields without
# breaking the parser).
# ---------------------------------------------------------------------------


class StartEvent(BaseModel):
    """Stream start marker (no payload beyond ``type``).

    Emitted once at the beginning of every creator-agent plan stream.
    """

    model_config = ConfigDict(extra="ignore")

    type: Literal["start"]
    message: Optional[str] = None


class ChunkEvent(BaseModel):
    """Partial plan text fragment (incremental rendering)."""

    model_config = ConfigDict(extra="ignore")

    type: Literal["chunk"]
    text: str
    index: Optional[int] = None


class AdviceEvent(BaseModel):
    """LLM self-reflection on the plan (severity-tagged)."""

    model_config = ConfigDict(extra="ignore")

    type: Literal["advice"]
    text: str
    severity: Optional[Literal["info", "warning", "critical"]] = None


class PreviewLabelEvent(BaseModel):
    """Preview label update (triggers preview-pane refresh)."""

    model_config = ConfigDict(extra="ignore")

    type: Literal["preview_label"]
    label: str


class DoneEvent(BaseModel):
    """Stream end marker with the final plan payload.

    ``plan`` is the canonical ``CreatorAgentPlanResponse`` DTO (re-exported
    in this file as ``CreatorAgentPlanResult`` for clarity).
    """

    model_config = ConfigDict(extra="ignore")

    type: Literal["done"]
    plan: CreatorAgentPlanResponse


class ErrorEvent(BaseModel):
    """Stream error marker (terminates the stream)."""

    model_config = ConfigDict(extra="ignore")

    type: Literal["error"]
    message: str
    code: Optional[str] = None


# Phase 126 v16.5 #N.10: ``status`` variant promoted from defensive extension.
class StatusEvent(BaseModel):
    """Stream progress marker emitted between LLM chunks.

    Backend emits ``status`` events at ``packages/lingwen-creator/src/
    lingwen_creator/content/agent.py:534, 537, 592`` — e.g.
    ``{"type": "status", "message": "正在分析写作范围…"}``,
    ``{"type": "status", "message": "正在连接模型…"}``, and
    ``{"type": "status", "message": "正在生成候选…"}``.

    Previously handled by a defensive local extension
    ``CreatorAgentStreamEvent | { type: 'status'; message: string }`` in
    ``apps/dashboard/src/composables/useCreatorAgent/useAgentTask.ts``;
    promoting to a canonical variant closes the type-contract gap and
    enables full type-safety for downstream consumers.
    """

    model_config = ConfigDict(extra="ignore")

    type: Literal["status"]
    message: str


# ---------------------------------------------------------------------------
# Discriminated union envelope.
#
# ``CreatorAgentStreamEvent`` is a ``BaseModel`` with ``type`` constrained to
# the union of valid event types, and a ``model_validator`` that enforces
# per-variant required-field rules. This preserves the standard Pydantic
# v2 ``model_validate(...)`` entry point while still rejecting unknown
# ``type`` values and missing required fields.
#
# On the TypeScript side, the variants are exported as separate ``interface``
# types by ``tooling/contracts/generate.py``; the dashboard-contracts shim
# composes the canonical ``CreatorAgentStreamEvent = StartEvent | ... |
# StatusEvent`` discriminated union from those exports.
# ---------------------------------------------------------------------------


class CreatorAgentStreamEvent(BaseModel):
    """Tagged-union envelope for creator-agent SSE stream events.

    Use ``CreatorAgentStreamEvent.model_validate(data)`` to dispatch on the
    ``type`` field. Returns a model instance with the variant-specific
    required fields populated.

    Per-variant requirements (enforced via ``_validate_variant``):
    - ``start``: optional ``message``
    - ``chunk``: required ``text``, optional ``index``
    - ``advice``: required ``text``, optional ``severity``
    - ``preview_label``: required ``label``
    - ``done``: required ``plan`` (CreatorAgentPlanResponse)
    - ``error``: required ``message``, optional ``code``
    - ``status``: required ``message``

    The ``type`` field is constrained to the literal union of valid event
    types — Pydantic v2 raises ``ValidationError`` on unknown ``type`` values.
    """

    model_config = ConfigDict(extra="ignore")

    type: Literal["start", "chunk", "advice", "preview_label", "done", "error", "status"]
    # Union of fields across all variants (optional per variant per above).
    message: Optional[str] = None
    text: Optional[str] = None
    index: Optional[int] = None
    severity: Optional[Literal["info", "warning", "critical"]] = None
    label: Optional[str] = None
    plan: Optional[CreatorAgentPlanResponse] = None
    code: Optional[str] = None

    @model_validator(mode="after")
    def _validate_variant(self) -> CreatorAgentStreamEvent:
        """Enforce per-variant required-field rules.

        Keeps strict discriminated-union semantics in a single BaseModel so
        ``model_validate(...)`` works at the call site.
        """
        if self.type == "chunk" and self.text is None:
            raise ValueError("chunk event requires 'text' field")
        if self.type == "advice" and self.text is None:
            raise ValueError("advice event requires 'text' field")
        if self.type == "preview_label" and self.label is None:
            raise ValueError("preview_label event requires 'label' field")
        if self.type == "done" and self.plan is None:
            raise ValueError("done event requires 'plan' field")
        if self.type == "error" and self.message is None:
            raise ValueError("error event requires 'message' field")
        if self.type == "status" and self.message is None:
            raise ValueError("status event requires 'message' field")
        return self


# ---------------------------------------------------------------------------
# Final result type alias (the ``plan`` field of ``DoneEvent``).
#
# Pure type alias (no runtime class). Matches the existing TS type alias
# ``CreatorAgentPlanResult = CreatorAgentPlanResponse``.
# ---------------------------------------------------------------------------


# Type alias for the canonical plan result. Pydantic v2 doesn't have a
# runtime class for aliases, so this is a Python-side hint for downstream
# consumers (matches the TS shape exactly).
CreatorAgentPlanResult = CreatorAgentPlanResponse


__all__ = [
    "AdviceEvent",
    "ChunkEvent",
    "CreatorAgentPlanResult",
    "CreatorAgentStreamEvent",
    "DoneEvent",
    "ErrorEvent",
    "PreviewLabelEvent",
    "StartEvent",
    "StatusEvent",
]
