"""Pydantic v2 DTOs for the creator bounded context — Volume + Settings domains.

Source of truth: lingwen_shared.contracts.python.creator (this file).
TypeScript types are auto-generated by tooling/contracts/generate.py.

Phase 126 v16.2.1 Task 3.2: Volume DTOs (~50 DTOs covering plan, merge/split,
diff, templates, template approvals, factory sync, summary).

Phase 126 v16.2.2 Task 5: Settings DTOs (~20 DTOs covering docs + history +
merge preferences + merge preset packages).

Each DTO mirrors the corresponding Pydantic model in
``apps/studio_api/models/`` (creator.py, creator_overview.py,
creator_volume_op.py, creator_template.py, creator_settings.py) so the
backend routes can re-export from this module without behavior change.

Conventions (v16.1 lessons):
- All DTOs use ``model_config = ConfigDict(extra="ignore")`` (forward compat).
- Optional fields use ``Optional[T] = None`` defaults.
- Self-referencing types resolve via ``from __future__ import annotations``.
"""
from __future__ import annotations

from typing import Any, Literal, Optional

from pydantic import BaseModel, ConfigDict, Field

# ---------------------------------------------------------------------------
# Plan core
# ---------------------------------------------------------------------------


class CreatorVolumePlanEntry(BaseModel):
    """Single volume plan row (label + chapter range + lock metadata)."""

    model_config = ConfigDict(extra="ignore")

    label: str
    start_chapter: int
    end_chapter: int
    core_conflict: str = ""
    locked: bool = False
    locked_at: Optional[str] = None


class CreatorVolumeDeviation(BaseModel):
    """Deviation row surfaced in plan response."""

    model_config = ConfigDict(extra="ignore")

    type: str
    severity: str
    chapter: int
    volume_label: Optional[str] = None
    message: str


class CreatorVolumePlanResponse(BaseModel):
    """Response shape for ``GET /api/creator/volume-plan``."""

    model_config = ConfigDict(extra="ignore")

    slug: str
    global_outline_path: str
    state_path: str
    revision: str
    volumes: list[CreatorVolumePlanEntry]
    locked_volume_count: int
    deviations: list[CreatorVolumeDeviation]
    deviation_count: int
    alert_count: int


class CreatorVolumePlanSaveRequest(BaseModel):
    """Request body for ``PUT /api/creator/volume-plan``."""

    model_config = ConfigDict(extra="ignore")

    volumes: list[CreatorVolumePlanEntry]
    expected_revision: Optional[str] = None


class CreatorVolumePlanDiffChange(BaseModel):
    """Single change entry in the volume plan diff payload."""

    model_config = ConfigDict(extra="ignore")

    type: str
    label: str
    message: str
    details: list[str] = []


class CreatorOutlineHighlightLine(BaseModel):
    """One outline line used by the diff side-by-side viewer."""

    model_config = ConfigDict(extra="ignore")

    text: str
    highlighted: bool = False


class CreatorVolumePlanDiffResponse(BaseModel):
    """Response shape for ``POST /api/creator/volume-plan/diff``."""

    model_config = ConfigDict(extra="ignore")

    has_changes: bool
    changes: list[CreatorVolumePlanDiffChange]
    global_outline_excerpt: str = ""
    global_outline_path: str = ""
    highlight_volume_labels: list[str] = []
    global_outline_lines: list[CreatorOutlineHighlightLine] = []


# ---------------------------------------------------------------------------
# Merge / split operations
# ---------------------------------------------------------------------------


class CreatorVolumeMergeRequest(BaseModel):
    """Request body for ``POST /api/creator/volume-plan/merge``."""

    model_config = ConfigDict(extra="ignore")

    volumes: list[CreatorVolumePlanEntry]
    start_index: int
    end_index: int
    label: Optional[str] = None
    core_conflict: Optional[str] = None


class CreatorVolumeMergeResponse(BaseModel):
    """Response shape for merge endpoint."""

    model_config = ConfigDict(extra="ignore")

    volumes: list[CreatorVolumePlanEntry]
    merged_label: str
    merged_range: str


class CreatorVolumeSplitRequest(BaseModel):
    """Request body for ``POST /api/creator/volume-plan/split``."""

    model_config = ConfigDict(extra="ignore")

    volumes: list[CreatorVolumePlanEntry]
    volume_index: int
    split_at_chapter: int
    first_label: Optional[str] = None
    second_label: Optional[str] = None


class CreatorVolumeSplitResponse(BaseModel):
    """Response shape for split endpoint."""

    model_config = ConfigDict(extra="ignore")

    volumes: list[CreatorVolumePlanEntry]
    first_label: str
    second_label: str
    first_range: str
    second_range: str


# ---------------------------------------------------------------------------
# Templates — info / list / changelog / version
# ---------------------------------------------------------------------------


class CreatorVolumeTemplateInfo(BaseModel):
    """Single volume template row (custom or factory)."""

    model_config = ConfigDict(extra="ignore")

    id: str
    name: str
    description: str
    builtin: bool = True
    scope: str = "builtin"
    version_label: Optional[str] = None
    version_semver_valid: bool = True
    version_changelog: list[dict[str, Any]] = []


class CreatorVolumeTemplateListResponse(BaseModel):
    """List of volume templates."""

    model_config = ConfigDict(extra="ignore")

    templates: list[CreatorVolumeTemplateInfo]


class CreatorVolumeTemplateChangelogDiffSummary(BaseModel):
    """Aggregated diff counters for a changelog entry."""

    model_config = ConfigDict(extra="ignore")

    changed: bool = False
    lines_added: int = 0
    lines_removed: int = 0
    snippet: list[str] = []


class CreatorVolumeTemplateChangelogVisualLine(BaseModel):
    """Visual diff line marker."""

    model_config = ConfigDict(extra="ignore")

    type: str
    text: str


class CreatorVolumeTemplateChangelogVisualDiff(BaseModel):
    """Visual before/after block for a changelog entry."""

    model_config = ConfigDict(extra="ignore")

    before: str = ""
    after: str = ""
    lines: list[CreatorVolumeTemplateChangelogVisualLine] = []


class CreatorVolumeTemplateChangelogEntry(BaseModel):
    """One changelog entry for a template version."""

    model_config = ConfigDict(extra="ignore")

    version_label: Optional[str] = None
    previous_label: Optional[str] = None
    changed_at: Optional[str] = None
    diff_summary: Optional[CreatorVolumeTemplateChangelogDiffSummary] = None
    visual_diff: Optional[CreatorVolumeTemplateChangelogVisualDiff] = None
    can_rollback: bool = False


class CreatorVolumeTemplateChangelogResponse(BaseModel):
    """Full changelog payload for a template."""

    model_config = ConfigDict(extra="ignore")

    template_id: str
    entries: list[CreatorVolumeTemplateChangelogEntry]


class CreatorVolumeTemplateRollbackRequest(BaseModel):
    """Request to roll back a template to a previous version."""

    model_config = ConfigDict(extra="ignore")

    version_label: Optional[str] = None
    changelog_index: Optional[int] = None


class CreatorVolumeTemplateRollbackResponse(BaseModel):
    """Response from a rollback operation."""

    model_config = ConfigDict(extra="ignore")

    id: str
    version_label: Optional[str] = None
    rolled_back_to: Optional[str] = None


class CreatorVolumeTemplateVersionRequest(BaseModel):
    """Request to set the version label on a template."""

    model_config = ConfigDict(extra="ignore")

    version_label: Optional[str] = None


class CreatorVolumeTemplateVersionResponse(BaseModel):
    """Response from a version-label update."""

    model_config = ConfigDict(extra="ignore")

    id: str
    version_label: Optional[str] = None


# ---------------------------------------------------------------------------
# Templates — save / rename / delete
# ---------------------------------------------------------------------------


class CreatorVolumeSaveTemplateRequest(BaseModel):
    """Request to save a custom template."""

    model_config = ConfigDict(extra="ignore")

    name: str
    volumes: list[CreatorVolumePlanEntry]
    max_chapter: Optional[int] = None
    description: Optional[str] = None
    version_label: Optional[str] = None


class CreatorVolumeSaveTemplateResponse(BaseModel):
    """Response after saving a custom template."""

    model_config = ConfigDict(extra="ignore")

    id: str
    name: str
    description: str


class CreatorVolumeDeleteTemplateResponse(BaseModel):
    """Response from deleting a custom template."""

    model_config = ConfigDict(extra="ignore")

    id: str
    deleted: bool


class CreatorVolumeRenameTemplateRequest(BaseModel):
    """Request to rename a custom template."""

    model_config = ConfigDict(extra="ignore")

    name: str
    description: Optional[str] = None
    version_label: Optional[str] = None


class CreatorVolumeRenameTemplateResponse(BaseModel):
    """Response from renaming a custom template."""

    model_config = ConfigDict(extra="ignore")

    id: str
    name: str
    description: str
    version_label: Optional[str] = None


# ---------------------------------------------------------------------------
# Templates — export / import / sync
# ---------------------------------------------------------------------------


class CreatorVolumeTemplateExportResponse(BaseModel):
    """Bundle of custom templates for export."""

    model_config = ConfigDict(extra="ignore")

    schema_version: str
    templates: list[dict[str, Any]]
    count: int


class CreatorVolumeTemplateImportRequest(BaseModel):
    """Request body for importing custom templates."""

    model_config = ConfigDict(extra="ignore")

    templates: list[dict[str, Any]]
    replace: bool = False


class CreatorVolumeTemplateImportResponse(BaseModel):
    """Response after importing custom templates."""

    model_config = ConfigDict(extra="ignore")

    imported: int
    total: int
    replaced: bool


class CreatorVolumeTemplateSyncSource(BaseModel):
    """A single project source available for template sync."""

    model_config = ConfigDict(extra="ignore")

    slug: str
    name: str
    template_count: int


class CreatorVolumeTemplateSyncSourcesResponse(BaseModel):
    """List of syncable projects (excluding current)."""

    model_config = ConfigDict(extra="ignore")

    sources: list[CreatorVolumeTemplateSyncSource]


class CreatorVolumeTemplateSyncRequest(BaseModel):
    """Request body for syncing templates from peer projects."""

    model_config = ConfigDict(extra="ignore")

    source_slugs: list[str]


class CreatorVolumeTemplateSyncResponse(BaseModel):
    """Response after syncing custom templates from peers."""

    model_config = ConfigDict(extra="ignore")

    imported: int
    total: int
    sources: list[str]


# ---------------------------------------------------------------------------
# Templates — apply-template (the main entry point for building a plan)
# ---------------------------------------------------------------------------


class CreatorVolumeApplyTemplateRequest(BaseModel):
    """Request to build a volume plan from a template."""

    model_config = ConfigDict(extra="ignore")

    template_id: str
    max_chapter: Optional[int] = None


class CreatorVolumeApplyTemplateResponse(BaseModel):
    """Built plan + template metadata after apply."""

    model_config = ConfigDict(extra="ignore")

    template_id: str
    template_name: str
    volumes: list[CreatorVolumePlanEntry]


# ---------------------------------------------------------------------------
# Factory templates (publish / pull / delete)
# ---------------------------------------------------------------------------


class CreatorVolumeFactoryPublishRequest(BaseModel):
    """Request to publish a custom template to the factory library."""

    model_config = ConfigDict(extra="ignore")

    template_id: str


class CreatorVolumeFactoryPublishResponse(BaseModel):
    """Response after publishing to the factory library."""

    model_config = ConfigDict(extra="ignore")

    id: str
    name: str
    description: str


class CreatorVolumeFactoryPullRequest(BaseModel):
    """Request to pull factory templates into the project."""

    model_config = ConfigDict(extra="ignore")

    template_ids: list[str]


class CreatorVolumeFactoryPullResponse(BaseModel):
    """Response after pulling factory templates."""

    model_config = ConfigDict(extra="ignore")

    imported: int
    total: int
    template_ids: list[str]


class CreatorVolumeFactoryDeleteResponse(BaseModel):
    """Response after deleting a factory template."""

    model_config = ConfigDict(extra="ignore")

    id: str
    deleted: bool


# ---------------------------------------------------------------------------
# Template approvals — request shapes
# ---------------------------------------------------------------------------


class CreatorVolumeTemplateApprovalSubmitRequest(BaseModel):
    """Submit a template version for approval review."""

    model_config = ConfigDict(extra="ignore")

    version_label: Optional[str] = None
    submit_note: str = ""


class CreatorVolumeTemplateApprovalResolveRequest(BaseModel):
    """Generic approve-side request (assignee + resolve note + force flag)."""

    model_config = ConfigDict(extra="ignore")

    assignee: str = ""
    resolve_note: str = ""
    force: bool = False


class CreatorVolumeTemplateApprovalRejectRequest(BaseModel):
    """Reject a template approval."""

    model_config = ConfigDict(extra="ignore")

    reason: str = ""
    resolve_note: str = ""


class CreatorVolumeTemplateApprovalTransferRequest(BaseModel):
    """Transfer a template approval to another assignee."""

    model_config = ConfigDict(extra="ignore")

    to_assignee: str
    note: str = ""


class CreatorVolumeTemplateApprovalBatchRequest(BaseModel):
    """Batch approve/reject a set of template approvals."""

    model_config = ConfigDict(extra="ignore")

    approval_ids: list[str]
    assignee: str = ""
    resolve_note: str = ""
    reason: str = ""
    force: bool = False


# ---------------------------------------------------------------------------
# Template approvals — result / response shapes
# ---------------------------------------------------------------------------


class CreatorVolumeTemplateApprovalBatchResult(BaseModel):
    """Per-item result of a batch approve/reject call."""

    model_config = ConfigDict(extra="ignore")

    id: str
    ok: bool
    status: Optional[str] = None
    chain_advanced: Optional[bool] = None
    error: Optional[str] = None


class CreatorVolumeTemplateApprovalBatchResponse(BaseModel):
    """Aggregate result of a batch approve/reject call."""

    model_config = ConfigDict(extra="ignore")

    approved: int = 0
    rejected: int = 0
    total: int
    results: list[CreatorVolumeTemplateApprovalBatchResult] = []


class CreatorVolumeTemplateApprovalDriftResponse(BaseModel):
    """Result of a snapshot-drift check on a saved approval."""

    model_config = ConfigDict(extra="ignore")

    approval_id: str
    template_id: str
    drifted: bool
    diff_summary: dict[str, Any] = {}
    force: bool = False


class CreatorVolumeTemplateApprovalSnapshotDiffResponse(BaseModel):
    """Snapshot diff preview between current template and the approved version."""

    model_config = ConfigDict(extra="ignore")

    approval_id: str
    template_id: str
    has_volumes_snapshot: bool = False
    diff_summary: dict[str, Any] = {}
    visual_diff: dict[str, Any] = {}


class CreatorVolumeTemplateApprovalOverdueResponse(BaseModel):
    """List of template approvals that have exceeded their SLA."""

    model_config = ConfigDict(extra="ignore")

    overdue_count: int
    approvals: list["CreatorVolumeTemplateApproval"] = []


class CreatorVolumeTemplateApprovalListResponse(BaseModel):
    """Filtered list of template approvals."""

    model_config = ConfigDict(extra="ignore")

    approvals: list["CreatorVolumeTemplateApproval"]


class CreatorVolumeTemplateApprovalHistoryResponse(BaseModel):
    """Most-recent template approval history."""

    model_config = ConfigDict(extra="ignore")

    approvals: list["CreatorVolumeTemplateApproval"]


class CreatorVolumeTemplateApprovalAuditExportResponse(BaseModel):
    """Schema-versioned audit export bundle."""

    model_config = ConfigDict(extra="ignore")

    schema_version: str = "1"
    count: int
    approvals: list["CreatorVolumeTemplateApproval"]


# ---------------------------------------------------------------------------
# Template approvals — config shapes
# ---------------------------------------------------------------------------


class CreatorVolumeTemplateApprovalChainConfig(BaseModel):
    """Chain configuration for template approvals."""

    model_config = ConfigDict(extra="ignore")

    required_steps: int = 2
    step_assignees: list[str] = []
    step_assignee_groups: Optional[list[list[str]]] = None


class CreatorVolumeTemplateApprovalSlaConfig(BaseModel):
    """SLA configuration for template approvals."""

    model_config = ConfigDict(extra="ignore")

    timeout_hours: int = 72
    email_on_submit: bool = True
    email_on_reject: bool = True
    email_on_overdue: bool = True


# ---------------------------------------------------------------------------
# Template approvals — row shape
# (declared last because other DTOs reference it via forward string)
# ---------------------------------------------------------------------------


class CreatorVolumeTemplateApproval(BaseModel):
    """One template approval row."""

    model_config = ConfigDict(extra="ignore")

    id: str
    template_id: str
    scope: str = "custom"
    status: str = "pending"
    version_label: Optional[str] = None
    previous_label: Optional[str] = None
    submitted_at: Optional[str] = None
    resolved_at: Optional[str] = None
    reject_reason: str = ""
    submit_note: str = ""
    resolve_note: str = ""
    current_assignee: str = ""
    current_assignees: list[str] = []
    or_signing: bool = False
    has_volumes_snapshot: bool = False
    chain_step: int = 1
    chain_total: int = 1
    chain_progress: str = "1/1"
    chain_log: list[dict[str, Any]] = []
    hours_pending: Optional[float] = None


# Rebuild forward references now that CreatorVolumeTemplateApproval exists.
# (Pydantic v2 requires explicit rebuild when using string annotations.)
CreatorVolumeTemplateApprovalOverdueResponse.model_rebuild()
CreatorVolumeTemplateApprovalListResponse.model_rebuild()
CreatorVolumeTemplateApprovalHistoryResponse.model_rebuild()
CreatorVolumeTemplateApprovalAuditExportResponse.model_rebuild()


# ---------------------------------------------------------------------------
# Volume summary (generate endpoint)
# ---------------------------------------------------------------------------


class CreatorVolumeSummaryGenerateRequest(BaseModel):
    """Request to generate a markdown volume summary for a chapter range."""

    model_config = ConfigDict(extra="ignore")

    start_chapter: int
    end_chapter: int


class CreatorVolumeSummaryGenerateResponse(BaseModel):
    """Response after generating a volume summary."""

    model_config = ConfigDict(extra="ignore")

    path: str
    written: bool = True


# ===========================================================================
# Settings Subdomain (Phase 126 v16.2.2 T2)
#
# Field types derived from:
# - apps/studio_api/models/creator_merge.py (existing Pydantic models)
# - infra/creator_settings_docs.py (creator_settings_docs_payload return shape)
# - infra/creator_settings_history.py (settings_history_payload return shape)
# - infra/creator_merge_preferences.py (~50 functions, mostly dict returns)
# ===========================================================================


# ---------------------------------------------------------------------------
# Settings Docs (5 DTOs)
# ---------------------------------------------------------------------------


class CreatorSettingsDocsResponse(BaseModel):
    """Return shape of ``creator_settings_docs_payload()``.

    Source of truth: apps/studio_api/models/creator_merge.py::CreatorSettingsDocsResponse
    """

    model_config = ConfigDict(extra="ignore")

    slug: str
    pillars_path: str
    global_outline_path: str
    pillars_text: str
    global_outline_text: str
    pillars_revision: str
    global_outline_revision: str


class CreatorSettingsDocsSaveRequest(BaseModel):
    """Request body for ``PUT /api/creator/settings-docs``.

    Source of truth: apps/studio_api/models/creator_merge.py::CreatorSettingsDocsSaveRequest
    """

    model_config = ConfigDict(extra="ignore")

    pillars_text: Optional[str] = None
    global_outline_text: Optional[str] = None
    expected_pillars_revision: Optional[str] = None
    expected_global_outline_revision: Optional[str] = None
    pillars_merge_source: Optional[str] = None
    global_outline_merge_source: Optional[str] = None
    merge_snapshot_id: Optional[str] = None
    pillars_merge_snapshot_id: Optional[str] = None
    global_outline_merge_snapshot_id: Optional[str] = None


class CreatorSettingsDiffPart(BaseModel):
    """Single-field diff block used by docs/three-way/merge responses."""

    model_config = ConfigDict(extra="ignore")

    changed: bool
    lines_added: int
    lines_removed: int
    snippet: list[str] = []


class CreatorSettingsDocsDiffResponse(BaseModel):
    """Return shape of ``preview_settings_docs_diff()``.

    Source of truth: apps/studio_api/models/creator_merge.py::CreatorSettingsDiffResponse
    """

    model_config = ConfigDict(extra="ignore")

    has_changes: bool
    pillars: CreatorSettingsDiffPart
    global_outline: CreatorSettingsDiffPart


class CreatorSettingsThreeWayPair(BaseModel):
    """One side of the three-way diff (pillars + global_outline)."""

    model_config = ConfigDict(extra="ignore")

    pillars: CreatorSettingsDiffPart
    global_outline: CreatorSettingsDiffPart


class CreatorSettingsThreeWayDiffResponse(BaseModel):
    """Return shape of ``preview_settings_three_way()``.

    Source of truth: apps/studio_api/models/creator_merge.py::CreatorSettingsThreeWayResponse
    """

    model_config = ConfigDict(extra="ignore")

    has_changes: bool
    pillars: CreatorSettingsDiffPart
    global_outline: CreatorSettingsDiffPart
    has_history: bool = False
    history_snapshot_id: Optional[str] = None
    disk_vs_history: Optional[CreatorSettingsThreeWayPair] = None
    editor_vs_history: Optional[CreatorSettingsThreeWayPair] = None


class CreatorSettingsMergeFieldPreview(BaseModel):
    """Per-field preview block for the merge-strategy endpoint."""

    model_config = ConfigDict(extra="ignore")

    source: str
    vs_disk: CreatorSettingsDiffPart
    vs_editor: CreatorSettingsDiffPart


class CreatorSettingsMergeStrategyResponse(BaseModel):
    """Return shape of ``preview_settings_merge_strategy()``.

    Source of truth: apps/studio_api/models/creator_merge.py::CreatorSettingsMergePreviewResponse
    """

    model_config = ConfigDict(extra="ignore")

    pillars: CreatorSettingsMergeFieldPreview
    global_outline: CreatorSettingsMergeFieldPreview


# ---------------------------------------------------------------------------
# Settings History (2 DTOs)
# ---------------------------------------------------------------------------


class CreatorSettingsHistorySnapshot(BaseModel):
    """One snapshot row returned by ``settings_history_payload()``."""

    model_config = ConfigDict(extra="ignore")

    id: str
    saved_at: Optional[str] = None
    label: str
    pillars_excerpt: str
    global_outline_excerpt: str
    pillars_lines: int
    global_outline_lines: int


class CreatorSettingsHistoryResponse(BaseModel):
    """Return shape of ``settings_history_payload()``.

    Source of truth: apps/studio_api/models/creator_merge.py::CreatorSettingsHistoryResponse
    """

    model_config = ConfigDict(extra="ignore")

    slug: str
    snapshots: list[CreatorSettingsHistorySnapshot] = []
    count: int


class CreatorSettingsHistoryRestoreRequest(BaseModel):
    """Request body for ``POST /api/creator/settings-docs/restore``.

    Source of truth: apps/studio_api/models/creator_merge.py::CreatorSettingsRestoreRequest
    """

    model_config = ConfigDict(extra="ignore")

    snapshot_id: str


# ---------------------------------------------------------------------------
# Merge Preferences (3 DTOs)
# ---------------------------------------------------------------------------


class CreatorMergePreferencesResponse(BaseModel):
    """Return shape of ``load_merge_preferences()`` and ``load_global_merge_preferences()``.

    Source of truth: apps/studio_api/models/creator_merge.py::CreatorMergePreferencesResponse
    """

    model_config = ConfigDict(extra="ignore")

    pillars_merge_source: str
    global_outline_merge_source: str
    merge_snapshot_id: Optional[str] = None
    pillars_merge_snapshot_id: Optional[str] = None
    global_outline_merge_snapshot_id: Optional[str] = None
    uses_global_default: bool = False


class CreatorMergePreferencesExportResponse(BaseModel):
    """Return shape of ``export_merge_preferences()``.

    Source of truth: apps/studio_api/models/creator_merge.py::CreatorMergePreferencesExportResponse
    """

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    schema_version: str
    project: dict[str, Any]
    global_prefs: dict[str, Any] = Field(default_factory=dict, alias="global")


class CreatorMergePreferencesImportRequest(BaseModel):
    """Request body for import-merge-preferences endpoint.

    Source of truth: apps/studio_api/models/creator_merge.py::CreatorMergePreferencesImportRequest
    """

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    schema_version: Optional[str] = None
    project: Optional[dict[str, Any]] = None
    global_prefs: Optional[dict[str, Any]] = Field(default=None, alias="global")
    scope: str = "project"


# ---------------------------------------------------------------------------
# Merge Presets — Package row (Summary + Detail share the same shape)
# ---------------------------------------------------------------------------


class CreatorMergePresetPackageSummary(BaseModel):
    """Summary row returned by ``list_merge_preset_packages()``.

    Source of truth: apps/studio_api/models/creator_merge.py::CreatorMergePresetPackage
    """

    model_config = ConfigDict(extra="ignore")

    id: str
    name: str
    description: str = ""
    builtin: bool = True
    scope: str = "builtin"
    version_label: Optional[str] = None
    version_semver_valid: bool = True
    depends_on: list[str] = []
    pillars_merge_source: str
    global_outline_merge_source: str


class CreatorMergePresetPackageDetail(BaseModel):
    """Detail view returned by ``get_merge_preset_package()``.

    Same row shape as Summary; reserved for future expansion (changelog, content).
    """

    model_config = ConfigDict(extra="ignore")

    id: str
    name: str
    description: str = ""
    builtin: bool = True
    scope: str = "builtin"
    version_label: Optional[str] = None
    version_semver_valid: bool = True
    depends_on: list[str] = []
    pillars_merge_source: str
    global_outline_merge_source: str


# ---------------------------------------------------------------------------
# Merge Presets — Graph (1 DTO + 2 nested types)
# ---------------------------------------------------------------------------


class CreatorMergePresetGraphNode(BaseModel):
    """Node in the merge preset dependency graph."""

    model_config = ConfigDict(extra="ignore")

    id: str
    name: str
    scope: str
    version_label: Optional[str] = None


class CreatorMergePresetGraphEdge(BaseModel):
    """Edge in the merge preset dependency graph."""

    model_config = ConfigDict(extra="ignore")

    from_pkg: str
    to: str
    relation: str = "depends_on"


class CreatorMergePresetGraphResponse(BaseModel):
    """Return shape of ``build_merge_preset_graph()``.

    Source of truth: apps/studio_api/models/creator_merge.py::CreatorMergePresetGraphResponse
    """

    model_config = ConfigDict(extra="ignore")

    node_count: int
    edge_count: int
    nodes: list[CreatorMergePresetGraphNode] = []
    edges: list[CreatorMergePresetGraphEdge] = []


# ---------------------------------------------------------------------------
# Merge Presets — Conflicts (1 DTO + 1 nested conflict row)
# ---------------------------------------------------------------------------


class CreatorMergePresetConflict(BaseModel):
    """Single conflict row used by both project and factory conflict responses.

    Source of truth: apps/studio_api/models/creator_merge.py::CreatorMergePresetConflict
    """

    model_config = ConfigDict(extra="ignore")

    type: str
    package_id: str
    dependency_id: Optional[str] = None
    path: list[str] = []
    message: str = ""


class CreatorMergePresetConflictsResponse(BaseModel):
    """Return shape of ``detect_merge_preset_conflicts()`` + factory variant.

    Source of truth: apps/studio_api/models/creator_merge.py::CreatorMergePresetConflictsResponse
    """

    model_config = ConfigDict(extra="ignore")

    conflict_count: int
    conflicts: list[CreatorMergePresetConflict] = []


# ---------------------------------------------------------------------------
# Merge Presets — Conflict Fix (1 DTO)
# ---------------------------------------------------------------------------


class CreatorMergePresetConflictFix(BaseModel):
    """Single fix suggestion row from ``suggest_merge_preset_fixes()``.

    Source of truth: apps/studio_api/models/creator_merge.py::CreatorMergePresetConflictFix
    """

    model_config = ConfigDict(extra="ignore")

    id: str
    conflict_type: str
    package_id: str
    action: str
    dependency_id: Optional[str] = None
    version_label: Optional[str] = None
    label: str = ""
    applicable: bool = False


# ---------------------------------------------------------------------------
# Merge Presets — Import preview (1 DTO)
# ---------------------------------------------------------------------------


class CreatorMergePresetImportPreviewResponse(BaseModel):
    """Return shape of ``preview_merge_preset_import_diff()`` (and preflight variant).

    Source of truth: apps/studio_api/models/creator_merge.py::CreatorMergePresetImportDiffPreviewResponse
    """

    model_config = ConfigDict(extra="ignore")

    added: list[str] = []
    updated: list[dict[str, Any]] = []
    removed: list[str] = []
    unchanged_count: int = 0
    replace: bool = False


# ---------------------------------------------------------------------------
# Merge Presets — Changelog (1 DTO + 1 nested entry)
# ---------------------------------------------------------------------------


class CreatorMergePresetChangelogEntry(BaseModel):
    """One changelog entry for a preset package.

    Source of truth: apps/studio_api/models/creator_merge.py::CreatorMergePresetChangelogEntry
    """

    model_config = ConfigDict(extra="ignore")

    changed_at: Optional[str] = None
    action: str = "update"
    changed_fields: list[str] = []
    snapshot: dict[str, Any] = Field(default_factory=dict)


class CreatorMergePresetChangelogResponse(BaseModel):
    """Return shape of ``list_merge_preset_changelog()``.

    Source of truth: apps/studio_api/models/creator_merge.py::CreatorMergePresetChangelogResponse
    """

    model_config = ConfigDict(extra="ignore")

    package_id: str
    entry_count: int
    entries: list[CreatorMergePresetChangelogEntry] = []


# ---------------------------------------------------------------------------
# Merge Presets — Publish (1 DTO)
# ---------------------------------------------------------------------------


class CreatorMergePresetPublishRequest(BaseModel):
    """Request body for ``publish_merge_preset_to_factory()``.

    Source of truth: apps/studio_api/models/creator_merge.py::CreatorMergePresetFactoryPublishRequest
    """

    model_config = ConfigDict(extra="ignore")

    package_id: str


# ---------------------------------------------------------------------------
# Merge Presets — Factory operations (1 generic DTO)
# ---------------------------------------------------------------------------


class CreatorFactoryMergePresetOperationResponse(BaseModel):
    """Generic factory operation result for publish / pull / delete / resolve_conflict.

    Source of truth: apps/studio_api/models/creator_merge.py::CreatorMergePresetFactoryPullResponse
    (shape matches the pull operation; other factory operations share enough fields
    to be modeled under one DTO — union widening left to typed wrapper layer).
    """

    model_config = ConfigDict(extra="ignore")

    imported: int
    skipped: int = 0
    total: int
    package_ids: list[str] = []
    skipped_package_ids: list[str] = []


# ---------------------------------------------------------------------------
# Merge Presets — Toposort (1 DTO)
# ---------------------------------------------------------------------------


class CreatorMergePresetToposortResponse(BaseModel):
    """Return shape of ``toposort_merge_preset_packages()``.

    Source of truth: apps/studio_api/models/creator_merge.py::CreatorMergePresetToposortResponse
    """

    model_config = ConfigDict(extra="ignore")

    order: list[str] = []
    cyclic: bool = False
    package_count: int = 0
    nodes: list[dict[str, Any]] = []
    edges: list[dict[str, str]] = []
    edge_count: int = 0


# ===========================================================================
# Onboarding — Phase 126 v16.2.3 (30 DTOs)
# ===========================================================================
# Source of truth: apps/studio_api/models/creator_onboarding.py
#                   apps/studio_api/models/creator_volume_op.py::CreatorWizardPanelCollapsedRequest
#                   apps/studio_api/models/creator_merge.py::CreatorDiffCollabNotesRequest/Response
# ===========================================================================


# ---------------------------------------------------------------------------
# Onboarding — Wizard panel + diff collab (cross-module)
# ---------------------------------------------------------------------------


class CreatorWizardPanelCollapsedRequest(BaseModel):
    """Request body for PUT /api/creator/onboarding/wizard-collapse.

    Source of truth: apps/studio_api/models/creator_volume_op.py::CreatorWizardPanelCollapsedRequest
    """

    model_config = ConfigDict(extra="ignore")

    collapsed: bool


class CreatorDiffCollabNotesRequest(BaseModel):
    """Request body for PUT /api/creator/onboarding/diff-collab-notes.

    Source of truth: apps/studio_api/models/creator_merge.py::CreatorDiffCollabNotesRequest
    """

    model_config = ConfigDict(extra="ignore")

    notes: dict[str, str] = {}


class CreatorDiffCollabNotesResponse(BaseModel):
    """Return shape of GET / PUT /api/creator/onboarding/diff-collab-notes.

    Source of truth: apps/studio_api/models/creator_merge.py::CreatorDiffCollabNotesResponse
    """

    model_config = ConfigDict(extra="ignore")

    notes: dict[str, str] = {}
    count: int = 0


# ---------------------------------------------------------------------------
# Onboarding — Wizard step (nested)
# ---------------------------------------------------------------------------


class CreatorOnboardingStep(BaseModel):
    """One step in the creator onboarding wizard.

    Source of truth: apps/studio_api/models/creator_onboarding.py::CreatorOnboardingStep
    """

    model_config = ConfigDict(extra="ignore")

    id: str
    title: str
    detail: str
    note: str = ""
    mentions: list[str] = []


# ---------------------------------------------------------------------------
# Onboarding — Main wizard payload (1 DTO)
# ---------------------------------------------------------------------------


class CreatorOnboardingResponse(BaseModel):
    """Return shape of GET /api/creator/onboarding.

    Source of truth: apps/studio_api/models/creator_onboarding.py::CreatorOnboardingResponse
    """

    model_config = ConfigDict(extra="ignore")

    slug: str
    creation_mode: str
    mode_label: str
    max_chapter: int
    steps: list[CreatorOnboardingStep]
    checklist_doc: str
    smoke_command: str
    onboarding_doc: str
    completed_step_ids: list[str] = []
    auto_completed_step_ids: list[str] = []
    step_notes: dict[str, str] = {}
    step_mentions: dict[str, list[str]] = {}
    unread_mention_count: int = 0
    progress_pct: int = 0
    wizard_panel_dismissed: bool = False
    wizard_panel_collapsed: bool = False


# ---------------------------------------------------------------------------
# Onboarding — Progress + Notes (3 DTOs)
# ---------------------------------------------------------------------------


class CreatorOnboardingProgressRequest(BaseModel):
    """Request body for PUT /api/creator/onboarding/progress.

    Source of truth: apps/studio_api/models/creator_onboarding.py::CreatorOnboardingProgressRequest
    """

    model_config = ConfigDict(extra="ignore")

    completed_step_ids: list[str] = []
    step_notes: Optional[dict[str, str]] = None


class CreatorOnboardingNotesRequest(BaseModel):
    """Request body for PUT /api/creator/onboarding/notes.

    Source of truth: apps/studio_api/models/creator_onboarding.py::CreatorOnboardingNotesRequest
    """

    model_config = ConfigDict(extra="ignore")

    step_notes: dict[str, str]


class CreatorOnboardingProgressResponse(BaseModel):
    """Return shape of PUT /api/creator/onboarding/progress.

    Source of truth: apps/studio_api/models/creator_onboarding.py::CreatorOnboardingProgressResponse
    """

    model_config = ConfigDict(extra="ignore")

    completed_step_ids: list[str]
    auto_completed_step_ids: list[str] = []
    step_notes: dict[str, str] = {}
    step_mentions: dict[str, list[str]] = {}
    progress_pct: int


# ---------------------------------------------------------------------------
# Onboarding — Notifications (6 DTOs + 2 nested)
# ---------------------------------------------------------------------------


class CreatorOnboardingNotification(BaseModel):
    """One notification row in the wizard @mention feed.

    Source of truth: apps/studio_api/models/creator_onboarding.py::CreatorOnboardingNotification
    """

    model_config = ConfigDict(extra="ignore")

    id: str
    step_id: str
    handle: str
    note_excerpt: str
    created_at: Optional[str] = None
    read: bool = False


class CreatorOnboardingNotificationsResponse(BaseModel):
    """Return shape of GET /api/creator/onboarding/notifications.

    Source of truth: apps/studio_api/models/creator_onboarding.py::CreatorOnboardingNotificationsResponse
    """

    model_config = ConfigDict(extra="ignore")

    notifications: list[CreatorOnboardingNotification]
    unread: int
    handles: list[str] = []


class CreatorOnboardingNotificationsAckRequest(BaseModel):
    """Request body for PUT /api/creator/onboarding/notifications/ack.

    Source of truth: apps/studio_api/models/creator_onboarding.py::CreatorOnboardingNotificationsAckRequest
    """

    model_config = ConfigDict(extra="ignore")

    notification_ids: list[str] = []
    all_notifications: bool = False
    handle: Optional[str] = None


class CreatorOnboardingNotificationsAckResponse(BaseModel):
    """Return shape of PUT /api/creator/onboarding/notifications/ack.

    Source of truth: apps/studio_api/models/creator_onboarding.py::CreatorOnboardingNotificationsAckResponse
    """

    model_config = ConfigDict(extra="ignore")

    acked: int
    unread: int


class CreatorOnboardingNotificationDigestStep(BaseModel):
    """One step entry inside a notification digest group.

    Source of truth: apps/studio_api/models/creator_onboarding.py::CreatorOnboardingNotificationDigestStep
    """

    model_config = ConfigDict(extra="ignore")

    step_id: str
    count: int


class CreatorOnboardingNotificationDigestGroup(BaseModel):
    """One handle group inside a notification digest.

    Source of truth: apps/studio_api/models/creator_onboarding.py::CreatorOnboardingNotificationDigestGroup
    """

    model_config = ConfigDict(extra="ignore")

    handle: str
    count: int
    steps: list[CreatorOnboardingNotificationDigestStep] = []
    latest_at: Optional[str] = None
    excerpts: list[str] = []


class CreatorOnboardingNotificationDigestResponse(BaseModel):
    """Return shape of POST /api/creator/onboarding/notifications/digest.

    Source of truth: apps/studio_api/models/creator_onboarding.py::CreatorOnboardingNotificationDigestResponse
    """

    model_config = ConfigDict(extra="ignore")

    unread: int
    group_count: int
    groups: list[CreatorOnboardingNotificationDigestGroup] = []


# ---------------------------------------------------------------------------
# Onboarding — Digest schedule + retry + dead-letter (10 DTOs)
# ---------------------------------------------------------------------------


class CreatorOnboardingDigestScheduleConfig(BaseModel):
    """Stored creator onboarding digest schedule.

    Source of truth: apps/studio_api/models/creator_onboarding.py::CreatorOnboardingDigestScheduleConfig
    """

    model_config = ConfigDict(extra="ignore")

    enabled: bool = False
    interval_hours: int = 24
    last_sent_at: Optional[str] = None
    channels: list[str] = ["webhook"]
    handle_channels: dict[str, list[str]] = {}
    quiet_hours_start: Optional[int] = None
    quiet_hours_end: Optional[int] = None
    handle_quiet_hours: dict[str, dict[str, int]] = {}
    channel_retry_config: dict[str, dict[str, int]] = {}


class CreatorOnboardingDigestScheduleSaveRequest(BaseModel):
    """Request body for PUT /api/creator/onboarding/digest/schedule.

    Source of truth: apps/studio_api/models/creator_onboarding.py::CreatorOnboardingDigestScheduleSaveRequest
    """

    model_config = ConfigDict(extra="ignore")

    enabled: bool = True
    interval_hours: int = 24
    channels: list[str] = ["webhook"]
    handle_channels: dict[str, list[str]] = {}
    quiet_hours_start: Optional[int] = None
    quiet_hours_end: Optional[int] = None
    handle_quiet_hours: dict[str, dict[str, int]] = {}
    channel_retry_config: dict[str, dict[str, int]] = {}


class CreatorOnboardingDigestDispatchStats(BaseModel):
    """Return shape of GET /api/creator/onboarding/digest/stats.

    Source of truth: apps/studio_api/models/creator_onboarding.py::CreatorOnboardingDigestDispatchStats
    """

    model_config = ConfigDict(extra="ignore")

    sent_total: int = 0
    failed_total: int = 0
    last_sent_at: Optional[str] = None
    last_failure_at: Optional[str] = None


class CreatorOnboardingDigestRetryItem(BaseModel):
    """One retry queue entry.

    Source of truth: apps/studio_api/models/creator_onboarding.py::CreatorOnboardingDigestRetryItem
    """

    model_config = ConfigDict(extra="ignore")

    channel: str
    error: str = ""
    queued_at: Optional[str] = None
    attempts: int = 0
    next_retry_at: Optional[str] = None


class CreatorOnboardingDigestRetryQueueResponse(BaseModel):
    """Return shape of GET /api/creator/onboarding/digest/retry-queue.

    Source of truth: apps/studio_api/models/creator_onboarding.py::CreatorOnboardingDigestRetryQueueResponse
    """

    model_config = ConfigDict(extra="ignore")

    item_count: int
    items: list[CreatorOnboardingDigestRetryItem] = []


class CreatorOnboardingDigestRetryProcessResponse(BaseModel):
    """Return shape of POST /api/creator/onboarding/digest/retry.

    Source of truth: apps/studio_api/models/creator_onboarding.py::CreatorOnboardingDigestRetryProcessResponse
    """

    model_config = ConfigDict(extra="ignore")

    retried: int
    remaining: int
    dead_letter_count: int = 0


class CreatorOnboardingDigestDeadLetterResponse(BaseModel):
    """Return shape of GET /api/creator/onboarding/digest/dead-letter.

    Source of truth: apps/studio_api/models/creator_onboarding.py::CreatorOnboardingDigestDeadLetterResponse
    """

    model_config = ConfigDict(extra="ignore")

    item_count: int
    items: list[CreatorOnboardingDigestRetryItem] = []


class CreatorOnboardingDigestDeadLetterReplayRequest(BaseModel):
    """Request body for POST /api/creator/onboarding/digest/dead-letter/replay.

    Source of truth: apps/studio_api/models/creator_onboarding.py::CreatorOnboardingDigestDeadLetterReplayRequest
    """

    model_config = ConfigDict(extra="ignore")

    index: int = 0


class CreatorOnboardingDigestDeadLetterReplayResponse(BaseModel):
    """Return shape of POST /api/creator/onboarding/digest/dead-letter/replay.

    Source of truth: apps/studio_api/models/creator_onboarding.py::CreatorOnboardingDigestDeadLetterReplayResponse
    """

    model_config = ConfigDict(extra="ignore")

    replayed: bool
    index: int
    channel: Optional[str] = None
    retry_queue_size: int = 0
    dead_letter_count: int = 0


class CreatorOnboardingDigestDispatchResponse(BaseModel):
    """Return shape of POST /api/creator/onboarding/digest/dispatch.

    Source of truth: apps/studio_api/models/creator_onboarding.py::CreatorOnboardingDigestDispatchResponse
    """

    model_config = ConfigDict(extra="ignore")

    sent: bool = False
    skipped: bool = False
    reason: Optional[str] = None
    last_sent_at: Optional[str] = None


# ---------------------------------------------------------------------------
# Onboarding — Webhook (3 DTOs)
# ---------------------------------------------------------------------------


class CreatorOnboardingWebhookConfig(BaseModel):
    """Stored creator onboarding webhook config.

    Source of truth: apps/studio_api/models/creator_onboarding.py::CreatorOnboardingWebhookConfig
    """

    model_config = ConfigDict(extra="ignore")

    enabled: bool = False
    url: str = ""
    mention_handles: list[str] = []
    signing_secret: str = ""


class CreatorOnboardingWebhookSaveRequest(BaseModel):
    """Request body for PUT /api/creator/onboarding/webhook.

    Source of truth: apps/studio_api/models/creator_onboarding.py::CreatorOnboardingWebhookSaveRequest
    """

    model_config = ConfigDict(extra="ignore")

    enabled: bool = True
    url: str = ""
    mention_handles: list[str] = []
    signing_secret: Optional[str] = None


class CreatorOnboardingWebhookDispatchResponse(BaseModel):
    """Generic webhook dispatch result.

    Source of truth: apps/studio_api/models/creator_onboarding.py::CreatorOnboardingWebhookDispatchResponse
    """

    model_config = ConfigDict(extra="ignore")

    dispatched: int = 0
    skipped: bool = False
    status: Optional[int] = None
    error: Optional[str] = None


# ---------------------------------------------------------------------------
# Onboarding — Email (2 DTOs)
# ---------------------------------------------------------------------------


class CreatorOnboardingEmailConfig(BaseModel):
    """Stored creator onboarding email config.

    Source of truth: apps/studio_api/models/creator_onboarding.py::CreatorOnboardingEmailConfig
    """

    model_config = ConfigDict(extra="ignore")

    enabled: bool = False
    to_addresses: list[str] = []
    mention_handles: list[str] = []
    smtp_host: str = ""
    smtp_port: int = 587
    smtp_user: str = ""
    smtp_use_tls: bool = True
    from_address: str = ""


class CreatorOnboardingEmailSaveRequest(BaseModel):
    """Request body for PUT /api/creator/onboarding/email.

    Source of truth: apps/studio_api/models/creator_onboarding.py::CreatorOnboardingEmailSaveRequest
    """

    model_config = ConfigDict(extra="ignore")

    enabled: bool = True
    to_addresses: list[str] = []
    mention_handles: list[str] = []
    smtp_host: str = ""
    smtp_port: int = 587
    smtp_user: str = ""
    smtp_password: Optional[str] = None
    smtp_use_tls: bool = True
    from_address: str = ""


# ---------------------------------------------------------------------------
# Content Subdomain (Phase 126 v16.2.4 T3) — 15 DTOs
# ---------------------------------------------------------------------------


class CreatorOverviewResponse(BaseModel):
    """Creator dashboard overview payload."""

    model_config = ConfigDict(extra="ignore")

    project_slug: str
    overview: dict[str, Any] = Field(default_factory=dict)
    last_updated: Optional[str] = None


class CreatorAgentPlanRequest(BaseModel):
    """Creator agent plan request (action label + optional context)."""

    model_config = ConfigDict(extra="ignore")

    action_label: str = Field(min_length=1)
    base_text: Optional[str] = None
    lens: Optional[str] = None
    provider_mode: Optional[str] = None


class CreatorAgentPlanResponse(BaseModel):
    """Creator agent plan response with results."""

    model_config = ConfigDict(extra="ignore")

    results: list[dict[str, Any]] = Field(default_factory=list)
    annotations: list[dict[str, Any]] = Field(default_factory=list)
    advice: Optional[str] = None


class CreatorBatchHistoryResponse(BaseModel):
    """Batch history jobs list response."""

    model_config = ConfigDict(extra="ignore")

    jobs: list[dict[str, Any]] = Field(default_factory=list)


class CreatorBatchHistoryExportResponse(BaseModel):
    """Batch history export response (count + jobs).

    Source of truth: apps/studio_api/models/creator_history.py::CreatorBatchHistoryExportResponse
    """

    model_config = ConfigDict(extra="ignore")

    schema_version: str = "1"
    count: int = 0
    jobs: list[dict[str, Any]] = Field(default_factory=list)


class CreatorPreferencesResponse(BaseModel):
    """Creator-level preferences payload."""

    model_config = ConfigDict(extra="ignore")

    creation_mode: Literal["companion", "advance", "studio"]
    quality_profile: str
    fail_severity: Optional[str] = None
    run_prose_calibration: bool = False
    run_llm_judge: bool = False
    run_golden_set: bool = False
    notify_per_chapter: bool = False
    advance_volume_summary: bool = False


class CreatorPreferencesSaveRequest(BaseModel):
    """Creator preferences save request (all fields optional for partial save)."""

    model_config = ConfigDict(extra="ignore")

    creation_mode: Optional[Literal["companion", "advance", "studio"]] = None
    quality_profile: Optional[str] = None
    fail_severity: Optional[str] = None
    run_prose_calibration: Optional[bool] = None
    run_llm_judge: Optional[bool] = None
    run_golden_set: Optional[bool] = None
    notify_per_chapter: Optional[bool] = None
    advance_volume_summary: Optional[bool] = None


class CreatorModelsResponse(BaseModel):
    """Available LLM models grouped by provider."""

    model_config = ConfigDict(extra="ignore")

    providers: list[dict[str, Any]] = Field(default_factory=list)


class CreatorLogicCheckResponse(BaseModel):
    """Creator logic check violations response."""

    model_config = ConfigDict(extra="ignore")

    violations: list[dict[str, Any]] = Field(default_factory=list)
    summary: Optional[str] = None


class CreatorChapterPreview(BaseModel):
    """Chapter preview with outline + body."""

    model_config = ConfigDict(extra="ignore")

    chapter_id: int
    project_slug: str
    outline: str
    body: str
    last_modified: Optional[str] = None


class CreatorOutlineSaveRequest(BaseModel):
    """Save chapter outline request (content required)."""

    model_config = ConfigDict(extra="ignore")

    chapter_id: int
    outline: str = Field(min_length=1)
    revision: Optional[str] = None


class CreatorBodySaveRequest(BaseModel):
    """Save chapter body request."""

    model_config = ConfigDict(extra="ignore")

    chapter_id: int
    body: str
    revision: Optional[str] = None
    metadata: Optional[dict[str, Any]] = None


class CreatorUiProfileState(BaseModel):
    """UI profile resolved state."""

    model_config = ConfigDict(extra="ignore")

    creation_mode: Literal["companion", "advance", "studio"]
    quality_profile: str
    advanced_visible: Optional[bool] = None
    wizard_visible: Optional[bool] = None
    dashboard_visible: Optional[bool] = None


class CreatorUiProfileSaveRequest(BaseModel):
    """UI profile save request."""

    model_config = ConfigDict(extra="ignore")

    creation_mode: Optional[Literal["companion", "advance", "studio"]] = None
    quality_profile: Optional[str] = None
    advanced_visible: Optional[bool] = None
    wizard_visible: Optional[bool] = None
    dashboard_visible: Optional[bool] = None


class CreatorDashboardOverview(BaseModel):
    """Creator dashboard overview (alternative layout for content.dashboard).

    Spec §3.3: dashboard variant of CreatorOverviewResponse — not yet wired in
    routes, kept as a forward-compat stub.
    """

    model_config = ConfigDict(extra="ignore")

    project_slug: str
    overview: dict[str, Any] = Field(default_factory=dict)


class CreatorDashboardChapterPreview(BaseModel):
    """Creator dashboard chapter preview (alternative layout for content.dashboard).

    Spec §3.3: dashboard variant of CreatorChapterPreview — not yet wired in
    routes, kept as a forward-compat stub.
    """

    model_config = ConfigDict(extra="ignore")

    chapter_id: int
    project_slug: str
    outline: str = ""
    body: str = ""
