"""Pydantic v2 DTOs for the CVG (Cross-Volume Graph) surface.

Source of truth: lingwen_shared.contracts.python.cvg (this file).
TypeScript types are auto-generated by tooling/contracts/generate.py.

Phase 126 v16.5 #N.7: Promoted from manual TS DTOs
(``packages/dashboard-contracts/src/shared/cvg.ts``).

Models defined here cover the dashboard surface of the studio API:
``GET /cvg/ripples``, ``/cvg/ripples/{id}``, ``/cvg/ripples/stats``,
``/cvg/reference-graph``, ``/cvg/ripples/{id}/audit``,
``/cvg/ripples/{id}/cascade``, ``/cvg/ripples/{id}/cascade/preview``,
``POST /cvg/ripples/{id}/{apply,reject,rollback}``,
``GET /ripples/cascade/{id}/runs``, ``GET /cascade/runs``,
``POST /ripples/cascade/{id}/runs/{runId}/cancel``,
``GET /ripples/cascade/{id}``.

# PYDANTIC-DRIFT: Backend storage shape in ``apps/studio_api/protocols.py``
(``Ripple*Response``, ``Cascade*Response``) uses field names like
``source_chapter`` / ``target_chapter`` that differ from the presentation
shape codified here (``source_volume``, ``impact_volumes``, ``chapter_id``).
Routes must continue to map backend storage → presentation at the response
boundary. Resolving backend re-export from lingwen-shared is v16.5 #N.8+
carryover.
"""
from __future__ import annotations

from typing import Any, Literal, Optional

from pydantic import BaseModel, ConfigDict, Field

# ---------------------------------------------------------------------------
# Ripple — list / detail / action / stats / audit
# ---------------------------------------------------------------------------


class RippleListItemResponse(BaseModel):
    """Single row in ``GET /cvg/ripples`` listing."""

    model_config = ConfigDict(extra="ignore")

    ripple_id: str
    chapter_id: int
    title: str
    status: str
    source_volume: int
    impact_volumes: list[int] = Field(default_factory=list)
    created_at: str
    updated_at: Optional[str] = None
    proposed_by: Optional[str] = None
    applies_count: Optional[int] = None


class RippleDetailResponse(RippleListItemResponse):
    """Full ripple detail returned by ``GET /cvg/ripples/{id}``.

    Extends ``RippleListItemResponse`` (presentation shape) — backend
    storage uses ``source_chapter`` / ``target_chapter`` which are
    projected to ``chapter_id`` + ``source_volume`` + ``impact_volumes``
    by the route layer.
    """

    model_config = ConfigDict(extra="ignore")

    description: Optional[str] = None
    evidence: Optional[dict[str, Any]] = None
    references: Optional[list[dict[str, Any]]] = None
    apply_metadata: Optional[dict[str, Any]] = None
    audit_trail: Optional[list["RippleAuditEntryResponse"]] = None


class RippleActionResponse(BaseModel):
    """Response payload for ripple apply / reject / rollback."""

    model_config = ConfigDict(extra="ignore")

    ripple_id: str
    action: str
    status: str
    applied_at: Optional[str] = None
    rejected_at: Optional[str] = None
    reason: Optional[str] = None
    message: Optional[str] = None


class RippleStatsResponse(BaseModel):
    """Aggregate ripple stats returned by ``GET /cvg/ripples/stats``."""

    model_config = ConfigDict(extra="ignore")

    total: int
    pending: int
    applied: int
    rejected: int
    rolled_back: int
    by_status: Optional[dict[str, int]] = None
    by_volume: Optional[dict[str, int]] = None


class RippleAuditEntryResponse(BaseModel):
    """Single audit-trail entry returned by ``GET /cvg/ripples/{id}/audit``."""

    model_config = ConfigDict(extra="ignore")

    audit_id: str
    ripple_id: str
    action: str
    actor: str
    timestamp: str
    reason: Optional[str] = None
    metadata: Optional[dict[str, Any]] = None


# ---------------------------------------------------------------------------
# Cascade — nodes / edges / response / preview
# ---------------------------------------------------------------------------


class CascadeNodeResponse(BaseModel):
    """Single node in a cascade graph."""

    model_config = ConfigDict(extra="ignore")

    node_id: str
    chapter_id: int
    title: str
    status: str
    depth: int


class CascadeEdgeResponse(BaseModel):
    """Single edge in a cascade graph."""

    model_config = ConfigDict(extra="ignore")

    source: str
    target: str
    relation: str
    weight: Optional[float] = None


class CascadeResponse(BaseModel):
    """Full cascade graph returned by ``GET /cvg/ripples/{id}/cascade``.

    Phase 126 v16.5 #N.10: extended with storage-shape fields (cascade_actions,
    generated_at, bfs_algorithm_version) so dashboard consumers in
    cascadeGraphUtils.js + useWorkflowSocket.js can read them via the typed wrapper.
    The dashboard currently reads these as untyped fields (PYDANTIC-DRIFT pre-N.10);
    adding them to the canonical enum closes the drift.
    """

    model_config = ConfigDict(extra="ignore")

    ripple_id: str
    nodes: list[CascadeNodeResponse]
    edges: list[CascadeEdgeResponse]
    total_nodes: int
    total_edges: int
    max_depth: int
    status: Optional[str] = None
    # Phase 126 v16.5 #N.10: storage-shape fields exposed for dashboard consumers
    cascade_actions: list[dict[str, Any]] = Field(default_factory=list)
    generated_at: Optional[str] = None
    bfs_algorithm_version: Literal["v1", "v2_weighted"] = "v1"


class CascadePreviewResponse(BaseModel):
    """Cascade preview returned by ``GET /cvg/ripples/{id}/cascade/preview``.

    Phase 126 v16.5 #N.10: extended with storage-shape aggregate counts
    (affected_*_count + estimated_change_count + cascade_*_count + max_depth)
    so dashboard apply-confirmation modal can read them via the typed wrapper.
    ``affected_chapters`` is defaulted (was required) because the storage-shape
    preview carries only aggregate counts, no per-chapter list.
    """

    model_config = ConfigDict(extra="ignore")

    ripple_id: str
    estimated_impact: int
    affected_chapters: list[int] = Field(default_factory=list)
    preview_tree: Optional[CascadeResponse] = None
    warnings: Optional[list[str]] = None
    # Phase 126 v16.5 #N.10: storage-shape aggregate counts
    affected_chapter_count: int = 0
    affected_character_count: int = 0
    affected_setting_count: int = 0
    estimated_change_count: int = 0
    cascade_node_count: int = 0
    cascade_edge_count: int = 0
    max_depth: int = 0


# ---------------------------------------------------------------------------
# Reference graph / cascade runs
# ---------------------------------------------------------------------------


class ReferenceGraphResponse(BaseModel):
    """Reference-graph payload returned by ``GET /cvg/reference-graph``."""

    model_config = ConfigDict(extra="ignore")

    nodes: list[dict[str, Any]]
    edges: list[dict[str, Any]]
    total_nodes: int
    total_edges: int
    by_dimension: Optional[dict[str, int]] = None


class CascadeRunResponse(BaseModel):
    """Cascade-run descriptor returned by ``GET /ripples/cascade/{id}/runs``.

    Phase 126 v16.5 #N.11.b: extended with storage-shape fields so the
    3 cascade-run endpoints (``get_ripple_cascade_runs``,
    ``list_all_cascade_runs``, ``post_ripple_cascade_run_cancel``) can serve
    canonical presentation shape via ``cvg_adapter.cascade_run_storage_to_presentation``.

    Storage CascadeRun (infra/cross_volume/storage.py:62-78) maps to a richer
    presentation shape: storage ``id`` is exposed as both ``run_id`` (str) and
    ``cascade_id`` (int). ``started_at`` and ``completed_at`` (datetime) are
    projected to ISO strings. ``cascade_nodes`` / ``cascade_edges`` /
    ``cascade_actions`` mirror the CascadeResponse extension for dashboard
    consumers. Cancel-specific fields (``cancelled_at`` + ``triggered_by``)
    and ``stats`` dict are populated by the route layer after adapter call.
    """

    model_config = ConfigDict(extra="ignore")

    run_id: str
    ripple_id: str
    status: str
    started_at: str
    finished_at: Optional[str] = None
    nodes_processed: int
    max_depth: int
    algorithm: Optional[str] = None
    metadata: Optional[dict[str, Any]] = None
    # Phase 126 v16.5 #N.11.b: storage-shape fields exposed for dashboard consumers
    cascade_id: Optional[int] = None  # storage 'id' (int PK)
    completed_at: Optional[str] = None  # storage 'completed_at' (datetime → ISO)
    depth_reached: int = 0
    cascade_nodes: list[CascadeNodeResponse] = Field(default_factory=list)
    cascade_edges: list[CascadeEdgeResponse] = Field(default_factory=list)
    cascade_actions: list[dict[str, Any]] = Field(default_factory=list)
    cancelled_at: Optional[str] = None
    triggered_by: Optional[str] = None
    stats: Optional[dict[str, Any]] = None


class CascadeCancelPayload(BaseModel):
    """Body / response for ``POST /ripples/cascade/{id}/runs/{runId}/cancel``."""

    model_config = ConfigDict(extra="ignore")

    run_id: str
    cancelled_at: Optional[str] = None
    reason: Optional[str] = None


# Resolve forward reference for RippleDetailResponse.audit_trail (string
# annotation → list[RippleAuditEntryResponse]). Required under
# ``from __future__ import annotations`` when a model references another
# model defined later in the same module.
RippleDetailResponse.model_rebuild()


__all__ = [
    "RippleListItemResponse",
    "RippleDetailResponse",
    "RippleActionResponse",
    "RippleStatsResponse",
    "RippleAuditEntryResponse",
    "CascadeNodeResponse",
    "CascadeEdgeResponse",
    "CascadeResponse",
    "CascadePreviewResponse",
    "ReferenceGraphResponse",
    "CascadeRunResponse",
    "CascadeCancelPayload",
]
