"""Pydantic v2 DTOs for the decisions bounded context.

Source of truth: lingwen_shared.contracts.python.decisions (this file).
TypeScript types are auto-generated by tooling/contracts/generate.py.

Phase 126 v16.5 #N.7: Promoted from manual TS DTOs
(``packages/dashboard-contracts/src/shared/decisions.ts``).

Models defined here cover the dashboard surface of the studio API:
``GET /decisions/pending``, ``/decisions/all``,
``POST /decisions/{id}/resolve``, ``/decisions/{id}/defer``,
``/decisions/{id}/cancel``.

# PYDANTIC-DRIFT: see ``health.py`` module docstring — backend storage
shapes are runtime-defined; ``context`` / resolution / reason fields are
``Optional[str]`` / ``Optional[dict[str, Any]]`` to permit nulls.
Resolving backend re-export from lingwen-shared is v16.5 #N.8+ carryover.
"""

from __future__ import annotations

from typing import Any, Optional

from pydantic import BaseModel, ConfigDict, Field


class DecisionResponse(BaseModel):
    """Single decision row returned by ``GET /decisions/pending`` / ``/decisions/all``."""

    model_config = ConfigDict(extra="ignore")

    decision_id: str
    kind: str
    node_id: str
    prompt: str
    options: list[str]
    priority: int
    status: str
    context: dict[str, Any] = Field(default_factory=dict)
    created_at: Optional[str] = None
    resolution: Optional[str] = None
    resolved_at: Optional[str] = None
    resolved_by: Optional[str] = None
    reason: Optional[str] = None


class ResolveDecisionRequest(BaseModel):
    """Body for ``POST /decisions/{id}/resolve``."""

    model_config = ConfigDict(extra="ignore")

    option: str
    resolved_by: str = "human"


class DeferDecisionRequest(BaseModel):
    """Body for ``POST /decisions/{id}/defer``."""

    model_config = ConfigDict(extra="ignore")

    reason: str = ""


class CancelDecisionRequest(BaseModel):
    """Body for ``POST /decisions/{id}/cancel``."""

    model_config = ConfigDict(extra="ignore")

    reason: str = ""


__all__ = [
    "DecisionResponse",
    "ResolveDecisionRequest",
    "DeferDecisionRequest",
    "CancelDecisionRequest",
]
