"""Pydantic v2 DTOs for the health/overview bounded context.

Source of truth: lingwen_shared.contracts.python.health (this file).
TypeScript types are auto-generated by tooling/contracts/generate.py.

Phase 126 v16.5 #N.7: Promoted from manual TS DTOs
(``packages/dashboard-contracts/src/shared/health.ts``).

Models defined here cover the dashboard surface of the studio API:
``GET /overview``, ``/chapters``, ``/production-records*``, ``/health``.

# PYDANTIC-DRIFT: Some fields in this module are a strict subset of the
``apps/studio_api/models/{health,chapter}.py`` storage shape, which uses
``dict`` / ``object`` types where these DTOs use strict ``dict[str, T]``.
Routes must continue to project from backend storage to these presentation
DTOs at the response boundary. Resolving backend re-export from
lingwen-shared is v16.5 #N.8+ carryover.
"""
from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict

# ---------------------------------------------------------------------------
# Database / memory health
# ---------------------------------------------------------------------------


class DatabaseStatus(BaseModel):
    """Database health snapshot returned by ``/health``."""

    model_config = ConfigDict(extra="ignore")

    status: str
    error: Optional[str] = None
    tables: Optional[int] = None
    records: Optional[int] = None


class MemoryUsage(BaseModel):
    """Process memory snapshot returned by ``/health``."""

    model_config = ConfigDict(extra="ignore")

    rss_mb: float
    vms_mb: float
    cpu_percent: float
    num_threads: int


class HealthResponse(BaseModel):
    """Overall service health returned by ``/health``."""

    model_config = ConfigDict(extra="ignore")

    status: str
    service: str
    timestamp: str
    uptime: float
    version: str
    python_version: str
    database: DatabaseStatus
    memory: MemoryUsage
    environment: Optional[str] = None
    features: Optional[dict[str, bool]] = None


# ---------------------------------------------------------------------------
# Overview / chapters
# ---------------------------------------------------------------------------


class OverviewResponse(BaseModel):
    """Aggregate counts returned by ``/overview``."""

    model_config = ConfigDict(extra="ignore")

    total_chapters: int
    total_hooks: int
    avg_hook_strength: float
    total_coolpoints: int
    avg_coolpoint_density: float


class ChapterData(BaseModel):
    """Per-chapter hook / coolpoint statistics."""

    model_config = ConfigDict(extra="ignore")

    chapter: int
    hook_count: int
    hook_strength_avg: float
    coolpoint_count: int
    coolpoint_density: float


class ChaptersResponse(BaseModel):
    """List of per-chapter statistics returned by ``/chapters``."""

    model_config = ConfigDict(extra="ignore")

    chapters: list[ChapterData]


# ---------------------------------------------------------------------------
# Production records / rollups / cost trend
# ---------------------------------------------------------------------------


class ProductionRecordResponse(BaseModel):
    """Single production record row."""

    model_config = ConfigDict(extra="ignore")

    record_id: str
    record_type: str
    chapter_num: Optional[int] = None
    chapter_range: Optional[str] = None
    operator: Optional[str] = None
    recorded_at: Optional[str] = None
    provider: Optional[str] = None
    total_cost_usd: Optional[float] = None
    emit_chapter_completed: Optional[bool] = None
    memory_context_source: Optional[str] = None
    stopped_reason: Optional[str] = None
    source_file: str


class ProductionRecordsResponse(BaseModel):
    """Directory listing of production records."""

    model_config = ConfigDict(extra="ignore")

    records_dir: str
    records: list[ProductionRecordResponse]


class ProductionBatchRollupResponse(BaseModel):
    """Per-batch rollup of cost / status."""

    model_config = ConfigDict(extra="ignore")

    record_id: str
    chapter_range: Optional[str] = None
    total_cost_usd: Optional[float] = None
    stopped_reason: Optional[str] = None
    recorded_at: Optional[str] = None
    source_file: str


class ProductionRollupResponse(BaseModel):
    """Aggregate rollup of all production records."""

    model_config = ConfigDict(extra="ignore")

    records_dir: str
    record_count: int
    pilot_count: int
    batch_count: int
    total_cost_usd: float
    chapters_with_records: int
    latest_recorded_at: Optional[str] = None
    batches: list[ProductionBatchRollupResponse]


class ProductionCostTrendPointResponse(BaseModel):
    """Single point on the cumulative cost trend."""

    model_config = ConfigDict(extra="ignore")

    recorded_at: Optional[str] = None
    record_id: str
    record_type: str
    label: str
    cost_usd: Optional[float] = None
    incremental_cost_usd: float
    cumulative_cost_usd: float


class ProductionCostTrendResponse(BaseModel):
    """Cumulative cost trend across the records directory."""

    model_config = ConfigDict(extra="ignore")

    records_dir: str
    point_count: int
    total_cost_usd: float
    points: list[ProductionCostTrendPointResponse]


__all__ = [
    "DatabaseStatus",
    "MemoryUsage",
    "HealthResponse",
    "OverviewResponse",
    "ChapterData",
    "ChaptersResponse",
    "ProductionRecordResponse",
    "ProductionRecordsResponse",
    "ProductionBatchRollupResponse",
    "ProductionRollupResponse",
    "ProductionCostTrendPointResponse",
    "ProductionCostTrendResponse",
]
