"""Pydantic v2 DTOs for the studio bounded context.

Source of truth: lingwen_shared.contracts.python.studio (this file).
TypeScript types are auto-generated by tooling/contracts/generate.py.

Phase 126 v16.5 #N.7: Promoted from manual TS DTOs
(``packages/dashboard-contracts/src/shared/studio.ts``).

Models defined here cover the dashboard surface of the studio API:
``GET /studio/projects``, ``/studio/active``, ``/studio/summary``,
``/studio/quality``, ``/studio/quality-report``, ``/studio/prose-diff``,
``/studio/prose-judge``, ``PUT /studio/active``,
``POST /studio/production/preflight``, ``/studio/production/run``, and
``GET /studio/production/jobs/*``.

# PYDANTIC-DRIFT: Field names mirror the manual TS surface; backend
storage (``apps/studio_api/models/studio.py``) uses snake_case but the
manual TS used the same shape, so no rename needed. Resolving backend
re-export from lingwen-shared is v16.5 #N.8+ carryover.
"""
from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict, Field


# ---------------------------------------------------------------------------
# Projects / active
# ---------------------------------------------------------------------------


class StudioProjectItem(BaseModel):
    """Single project entry returned by ``/studio/projects``."""

    model_config = ConfigDict(extra="ignore")

    slug: str
    name: str
    role: str
    root: str
    location: str


class StudioProjectsResponse(BaseModel):
    """Project listing returned by ``/studio/projects``."""

    model_config = ConfigDict(extra="ignore")

    projects: list[StudioProjectItem]
    active_slug: Optional[str] = None


class StudioActiveResponse(BaseModel):
    """Active project descriptor returned by ``/studio/active``."""

    model_config = ConfigDict(extra="ignore")

    slug: str
    name: str
    root: str
    role: str


class StudioSetActiveRequest(BaseModel):
    """Body for ``PUT /studio/active``."""

    model_config = ConfigDict(extra="ignore")

    slug: str


# ---------------------------------------------------------------------------
# Summary / quality
# ---------------------------------------------------------------------------


class StudioSummaryResponse(BaseModel):
    """Project summary returned by ``/studio/summary``."""

    model_config = ConfigDict(extra="ignore")

    slug: str
    name: str
    role: str
    root: str
    location: str
    max_chapter: int
    genre: str
    chapter_count: int
    latest_chapter: int
    outline_count: int
    golden_chapters: list[int]
    has_golden_set: bool
    pilot_records_dir: str
    pilot_record_count: int
    pillars_ok: bool
    pillars_path: str
    creation_mode: str = "studio"
    quality_profile: str = "studio_full"


class StudioQualityResponse(BaseModel):
    """Project quality snapshot returned by ``/studio/quality``."""

    model_config = ConfigDict(extra="ignore")

    slug: str
    pillars_ok: bool
    pillars_path: str
    require_chapter_outline: bool
    max_chapter: int
    chapters_written: int
    outlines_present: int
    coverage_pct: float
    missing_outlines: list[int]
    missing_bodies: list[int]
    golden_set_status: str
    golden_regression_cmd: str


# ---------------------------------------------------------------------------
# Quality report + prose heatmap
# ---------------------------------------------------------------------------


class StudioQualityReportIssue(BaseModel):
    """Single quality-report issue."""

    model_config = ConfigDict(extra="ignore")

    severity: str
    issue_type: str
    chapter: int
    description: str


class StudioQualityReportChapter(BaseModel):
    """Per-chapter quality-report entry."""

    model_config = ConfigDict(extra="ignore")

    chapter: int
    word_count: int
    issue_count: int
    issues: list[StudioQualityReportIssue]


class StudioProseHeatmapChapter(BaseModel):
    """Per-chapter heat-map cell."""

    model_config = ConfigDict(extra="ignore")

    chapter: int
    issue_count: int
    prose_p1: int
    prose_total: int
    structural_total: int
    heat: float


class StudioProseHeatmap(BaseModel):
    """Heat-map summary across chapters."""

    model_config = ConfigDict(extra="ignore")

    chapters: list[StudioProseHeatmapChapter]
    max_prose_per_chapter: Optional[int] = None
    total_prose_issues: Optional[int] = None
    total_prose_p1: Optional[int] = None


class StudioQualityReportResponse(BaseModel):
    """Full quality-report payload returned by ``/studio/quality-report``."""

    model_config = ConfigDict(extra="ignore")

    slug: str
    available: bool
    path: str
    total: int
    p0: int
    p1: int
    p2: int
    p3: int
    generated_at: Optional[str] = None
    chapters: list[StudioQualityReportChapter]
    prose_heatmap: StudioProseHeatmap


# ---------------------------------------------------------------------------
# Prose diff
# ---------------------------------------------------------------------------


class StudioProseDiffTotals(BaseModel):
    """Aggregate delta for a prose diff."""

    model_config = ConfigDict(extra="ignore")

    p0: int = 0
    p1: int = 0
    total: int = 0
    prose_p1: int = 0
    prose_total: int = 0


class StudioProseDiffChapter(BaseModel):
    """Per-chapter prose-diff entry."""

    model_config = ConfigDict(extra="ignore")

    chapter: int
    before_prose_p1: int
    after_prose_p1: int
    delta_prose_p1: int
    before_prose_total: int
    after_prose_total: int
    delta_prose_total: int


class StudioProseDiffResponse(BaseModel):
    """Prose-diff payload returned by ``/studio/prose-diff``."""

    model_config = ConfigDict(extra="ignore")

    slug: str
    available: bool
    reason: Optional[str] = None
    snapshot_path: Optional[str] = None
    report_path: Optional[str] = None
    save_command: Optional[str] = None
    before_captured_at: Optional[str] = None
    after_captured_at: Optional[str] = None
    total_delta: Optional[StudioProseDiffTotals] = None
    chapters: list[StudioProseDiffChapter] = Field(default_factory=list)
    improved_count: int = 0
    regressed_count: int = 0
    has_regression: bool = False
    net_prose_p1_delta: int = 0


# ---------------------------------------------------------------------------
# Prose judge
# ---------------------------------------------------------------------------


class StudioProseJudgeRating(BaseModel):
    """Single judge rating on a dimension."""

    model_config = ConfigDict(extra="ignore")

    dimension: str
    score: float
    evidence: str
    action: str


class StudioProseJudgeChapter(BaseModel):
    """Per-chapter judge verdict with rolled-up avg score."""

    model_config = ConfigDict(extra="ignore")

    chapter: int
    avg_score: float
    ratings: list[StudioProseJudgeRating]


class StudioProseJudgeSignal(BaseModel):
    """A signal flagged for review by the prose judge."""

    model_config = ConfigDict(extra="ignore")

    chapter: int
    issue_type: Optional[str] = None
    dimension: Optional[str] = None
    judge_score: float
    description: Optional[str] = None
    evidence: Optional[str] = None


class StudioProseJudgeResponse(BaseModel):
    """Prose-judge payload returned by ``/studio/prose-judge``."""

    model_config = ConfigDict(extra="ignore")

    slug: str
    available: bool
    reason: Optional[str] = None
    report_path: Optional[str] = None
    generate_command: Optional[str] = None
    source: Optional[str] = None
    judged_at: Optional[str] = None
    golden_chapters: list[int] = Field(default_factory=list)
    weighted_avg: float = 0.0
    chapters: list[StudioProseJudgeChapter] = Field(default_factory=list)
    high_priority_count: int = 0
    false_positive_candidate_count: int = 0
    review_needed_count: int = 0
    high_priority: list[StudioProseJudgeSignal] = Field(default_factory=list)
    false_positive_candidates: list[StudioProseJudgeSignal] = Field(
        default_factory=list
    )
    review_needed: list[StudioProseJudgeSignal] = Field(default_factory=list)


# ---------------------------------------------------------------------------
# Preflight + batch run
# ---------------------------------------------------------------------------


class StudioPreflightChapter(BaseModel):
    """Per-chapter preflight result."""

    model_config = ConfigDict(extra="ignore")

    chapter: int
    ok: bool
    message: str


class StudioPreflightRequest(BaseModel):
    """Body for ``POST /studio/production/preflight``."""

    model_config = ConfigDict(extra="ignore")

    start_chapter: int
    end_chapter: int
    mode: Optional[str] = None


class StudioPreflightResponse(BaseModel):
    """Preflight response returned by ``/studio/production/preflight``."""

    model_config = ConfigDict(extra="ignore")

    slug: str
    mode: str
    start_chapter: int
    end_chapter: int
    all_ok: bool
    chapters: list[StudioPreflightChapter]
    batch_command: str


class StudioBatchRunRequest(BaseModel):
    """Body for ``POST /studio/production/run``."""

    model_config = ConfigDict(extra="ignore")

    start_chapter: int
    end_chapter: int
    mode: Optional[str] = None
    budget_usd: Optional[float] = None
    skip_preflight: Optional[bool] = None


class StudioBatchJobResponse(BaseModel):
    """Background job descriptor returned by ``/studio/production/jobs/*``."""

    model_config = ConfigDict(extra="ignore")

    job_id: str
    slug: str
    start_chapter: int
    end_chapter: int
    budget_usd: float
    mode: str
    status: str
    pid: Optional[int] = None
    log_path: str
    started_at: str
    finished_at: Optional[str] = None
    exit_code: Optional[int] = None
    error: Optional[str] = None
    log_tail: Optional[str] = None


__all__ = [
    "StudioProjectItem",
    "StudioProjectsResponse",
    "StudioActiveResponse",
    "StudioSetActiveRequest",
    "StudioSummaryResponse",
    "StudioQualityResponse",
    "StudioQualityReportIssue",
    "StudioQualityReportChapter",
    "StudioProseHeatmapChapter",
    "StudioProseHeatmap",
    "StudioQualityReportResponse",
    "StudioProseDiffTotals",
    "StudioProseDiffChapter",
    "StudioProseDiffResponse",
    "StudioProseJudgeRating",
    "StudioProseJudgeChapter",
    "StudioProseJudgeSignal",
    "StudioProseJudgeResponse",
    "StudioPreflightChapter",
    "StudioPreflightRequest",
    "StudioPreflightResponse",
    "StudioBatchRunRequest",
    "StudioBatchJobResponse",
]