"""Pydantic v2 DTOs for the workflows bounded context.

Source of truth: lingwen_shared.contracts.python.workflows (this file).
TypeScript types are auto-generated by tooling/contracts/generate.py.

Phase 126 v16.5 #N.7: Promoted from manual TS DTOs
(``packages/dashboard-contracts/src/shared/workflows.ts``).

Models defined here cover the dashboard surface of the studio API:
``GET /workflows/list``, ``/workflows/active``, ``/workflows/{name}/mermaid``,
``POST /workflows/run``, ``POST /workflows/resume``.

The status response uses ``dict[str, Any]`` and ``list[dict[str, Any]]``
for the dynamic budget / score / decision maps because the backend shapes
are runtime-defined (per-scenario / per-tier / per-day). Routes project
the runtime dicts into these models at the response boundary.

# PYDANTIC-DRIFT: see ``health.py`` module docstring — backend storage
uses untyped dicts; presentation DTOs here use ``dict[str, Any]`` for
backward compat. Resolving backend re-export is v16.5 #N.8+ carryover.
"""

from __future__ import annotations

from typing import Any, Optional

from pydantic import BaseModel, ConfigDict, Field


class WorkflowListItem(BaseModel):
    """Single workflow descriptor in ``/workflows/list`` response."""

    model_config = ConfigDict(extra="ignore")

    name: str
    path: str
    node_count: int
    has_decision_nodes: bool


class RunWorkflowRequest(BaseModel):
    """Body for ``POST /workflows/run``."""

    model_config = ConfigDict(extra="ignore")

    workflow_name: str
    initial_inputs: Optional[dict[str, Any]] = None
    start_nodes: Optional[list[str]] = None
    max_backtracks: int = 2
    base_dir: Optional[str] = None
    cost_budget_usd: Optional[float] = None


class ResumeWorkflowRequest(BaseModel):
    """Body for ``POST /workflows/resume``."""

    model_config = ConfigDict(extra="ignore")

    decision_id: str
    option: str
    resolved_by: str = "human"
    cost_budget_usd: Optional[float] = None


class WorkflowStatusResponse(BaseModel):
    """Live status payload returned by ``/workflows/active``."""

    model_config = ConfigDict(extra="ignore")

    workflow_name: Optional[str] = None
    is_active: Optional[bool] = None
    completed: Optional[int] = None
    failed: Optional[int] = None
    paused: Optional[bool] = None
    paused_nodes: Optional[list[str]] = None
    node_count: Optional[int] = None
    steps: Optional[int] = None
    total_cost_usd: Optional[float] = None
    pending_decisions: Optional[list[dict[str, Any]]] = None
    executions: Optional[dict[str, str]] = None
    score_data: Optional[dict[str, dict[str, Any]]] = None
    cost_by_scenario: Optional[dict[str, float]] = None
    cost_by_tier: Optional[dict[str, float]] = None
    cost_by_day: Optional[dict[str, float]] = None
    cost_by_day_per_tier: Optional[dict[str, dict[str, float]]] = None
    cost_budget_status: Optional[dict[str, Any]] = None
    budget_per_day: Optional[dict[str, Any]] = None
    budget_per_week: Optional[dict[str, Any]] = None
    budget_by_tier: Optional[dict[str, dict[str, Any] | None]] = None
    incremental_backfill: Optional[dict[str, Any]] = None
    production_summary: Optional[dict[str, Any]] = None


class WorkflowMermaidResponse(BaseModel):
    """Mermaid diagram + per-node status returned by ``/workflows/{name}/mermaid``."""

    model_config = ConfigDict(extra="ignore")

    workflow_name: str
    mermaid: str
    node_count: int
    has_decision_nodes: bool
    status_applied: bool = False
    node_statuses: dict[str, str] = Field(default_factory=dict)


__all__ = [
    "WorkflowListItem",
    "RunWorkflowRequest",
    "ResumeWorkflowRequest",
    "WorkflowStatusResponse",
    "WorkflowMermaidResponse",
]
