"""Pydantic v2 DTOs for the world bounded context.

Source of truth: lingwen_shared.contracts.python.world (this file).
TypeScript types are auto-generated by tooling/contracts/generate.py.

This file is the v16.1 starter set. Additions go here, not in routes/world.py
(which now imports from this module and re-exports for backward compat).
"""

from __future__ import annotations

from typing import Any, Literal, Mapping

from pydantic import BaseModel, ConfigDict, Field

# ---------------------------------------------------------------------------
# Character
# ---------------------------------------------------------------------------


class CharacterDTO(BaseModel):
    """Character row from the world DB (characters table).

    Mirrors ``infra/world_db/queries/characters.py::row_to_dict`` output shape.
    """

    model_config = ConfigDict(extra="ignore")

    id: int
    slug: str
    name: str
    canon_level: Literal["Draft", "Secondary", "Primary"]
    status: str | None = None
    first_chapter: int | None = None
    last_seen_chapter: int | None = None
    attributes: Mapping[str, Any] | None = None
    aliases: list[str] | None = None
    notes: str | None = None


# ---------------------------------------------------------------------------
# Faction
# ---------------------------------------------------------------------------


class FactionDTO(BaseModel):
    """Faction row from the world DB (faction table)."""

    model_config = ConfigDict(extra="ignore")

    id: int
    slug: str
    name: str
    description: str | None = None
    canon_level: Literal["Draft", "Secondary", "Primary"] = "Draft"


# ---------------------------------------------------------------------------
# Lore
# ---------------------------------------------------------------------------


class LoreDTO(BaseModel):
    """Lore (world book entry) row from the world DB (lore table)."""

    model_config = ConfigDict(extra="ignore")

    id: int
    category: str
    title: str
    body: str
    canon_level: Literal["Draft", "Secondary", "Primary"] = "Draft"


# ---------------------------------------------------------------------------
# Timeline event
# ---------------------------------------------------------------------------


class TimelineEventDTO(BaseModel):
    """Timeline event row from the world DB (timeline_event table)."""

    model_config = ConfigDict(extra="ignore")

    id: int
    project_slug: str
    chapter_number: int
    title: str
    description: str | None = None
    characters_involved: list[int] | None = None
    canon_level: Literal["Draft", "Secondary", "Primary"] = "Draft"


# ---------------------------------------------------------------------------
# Proposal (LLM agent extraction result)
# ---------------------------------------------------------------------------


class CharacterUpdatePayload(BaseModel):
    """Subset of Character fields accepted by ``character.update`` proposals.

    Each field is optional because the LLM may only emit a partial patch.
    Mirrors ``infra/world_db/agent_schemas.py::CharacterUpdatePayload``
    (Phase 118). Kept here so all character DTOs live in one place.
    """

    name: str | None = None
    canon_level: Literal["Draft", "Secondary", "Primary"] | None = None
    status: str | None = None
    first_chapter: int | None = None
    last_seen_chapter: int | None = None
    attributes: dict | None = None
    aliases: list[str] | None = None
    notes: str | None = None


class ProposalDTO(BaseModel):
    """One proposal returned by the LLM extractor (proposal table row shape)."""

    model_config = ConfigDict(extra="ignore")

    id: int | None = None
    kind: Literal["character.update", "character.create"]
    target_kind: Literal["character", "faction"] | None = None
    target_id: int = 0
    payload: CharacterUpdatePayload
    source: Literal["agent"] = "agent"
    source_context: str | None = None
    confidence: Literal["high", "medium", "low"] = "medium"
    status: Literal["pending", "accepted", "rejected", "applied"] = "pending"
